SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'PERU'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'PERU')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'PERU'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'PERU')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ARGENTINA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'ARGENTINA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'EGYPT')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'EGYPT')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'BRAZIL'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'BRAZIL')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAQ'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'IRAQ')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'VIETNAM'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'VIETNAM')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'SAUDI ARABIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'EGYPT')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOZAMBIQUE'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'MOZAMBIQUE')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CANADA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'CANADA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CHINA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'CHINA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'KENYA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'KENYA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'RUSSIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'RUSSIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'SAUDI ARABIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAQ'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'IRAQ')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'INDIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'EGYPT')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOROCCO'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'MOROCCO')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ETHIOPIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'ETHIOPIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'SAUDI ARABIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CANADA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'CANADA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JAPAN'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'JAPAN')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'EGYPT')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'EGYPT')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'FRANCE'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'FRANCE')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'BRAZIL'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'BRAZIL')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JORDAN'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'JORDAN')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'EGYPT')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CANADA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'CANADA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CANADA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'CANADA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'BRAZIL'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'BRAZIL')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'VIETNAM'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'VIETNAM')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ETHIOPIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'ETHIOPIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'FRANCE'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'FRANCE')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'FRANCE'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'FRANCE')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAQ'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'IRAQ')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOZAMBIQUE'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'MOZAMBIQUE')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'PERU'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'PERU')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAN'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'IRAN')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'SAUDI ARABIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ARGENTINA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'ARGENTINA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CANADA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'CANADA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED STATES'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'UNITED STATES')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'FRANCE'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'FRANCE')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'KENYA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'KENYA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'BRAZIL'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'BRAZIL')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'SAUDI ARABIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED KINGDOM'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'UNITED KINGDOM')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED STATES'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'UNITED STATES')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'EGYPT')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAQ'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'IRAQ')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JAPAN'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'JAPAN')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'BRAZIL'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'BRAZIL')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'GERMANY'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'GERMANY')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'GERMANY'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'GERMANY')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOZAMBIQUE'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'MOZAMBIQUE')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'INDIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'RUSSIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'RUSSIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED STATES'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'UNITED STATES')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'INDIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED KINGDOM'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'UNITED KINGDOM')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'INDIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'VIETNAM'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'VIETNAM')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ALGERIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'ALGERIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'ROMANIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'FRANCE'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'FRANCE')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JORDAN'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'JORDAN')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'RUSSIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'RUSSIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CANADA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'CANADA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ETHIOPIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'ETHIOPIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CHINA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'CHINA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ARGENTINA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'ARGENTINA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOROCCO'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'MOROCCO')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ALGERIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'ALGERIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'VIETNAM'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'VIETNAM')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'SAUDI ARABIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED KINGDOM'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'UNITED KINGDOM')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'PERU'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'PERU')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDONESIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'INDONESIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOROCCO'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'MOROCCO')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'ROMANIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'KENYA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'KENYA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JORDAN'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'JORDAN')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAQ'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'IRAQ')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ARGENTINA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'ARGENTINA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JORDAN'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'JORDAN')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED KINGDOM'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'UNITED KINGDOM')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDONESIA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'INDONESIA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'KENYA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'KENYA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ARGENTINA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'ARGENTINA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CANADA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'CANADA')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'GERMANY'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'GERMANY')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'EGYPT')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED KINGDOM'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'UNITED KINGDOM')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JAPAN'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'JAPAN')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'GERMANY'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'GERMANY')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'VIETNAM'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'VIETNAM')
ORDER BY VALUE DESC;

---

SELECT PS_PARTKEY, SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP, SUPPLIER, NATION
WHERE PS_SUPPKEY = S_SUPPKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CHINA'
GROUP BY PS_PARTKEY
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) >
		(SELECT SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.001000
			FROM PARTSUPP, SUPPLIER, NATION
			WHERE PS_SUPPKEY = S_SUPPKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND N_NAME = 'CHINA')
ORDER BY VALUE DESC;
