CREATE VIEW REVENUE0 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-12-01'
		AND L_SHIPDATE < '1995-03-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE0
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE0)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE0;

---

CREATE VIEW REVENUE1 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-08-01'
		AND L_SHIPDATE < '1995-11-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE1
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE1)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE1;

---

CREATE VIEW REVENUE2 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-07-01'
		AND L_SHIPDATE < '1995-10-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE2
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE2)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE2;

---

CREATE VIEW REVENUE3 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-08-01'
		AND L_SHIPDATE < '1997-11-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE3
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE3)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE3;

---

CREATE VIEW REVENUE4 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-04-01'
		AND L_SHIPDATE < '1994-07-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE4
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE4)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE4;

---

CREATE VIEW REVENUE5 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-03-01'
		AND L_SHIPDATE < '1995-06-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE5
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE5)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE5;

---

CREATE VIEW REVENUE6 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-07-01'
		AND L_SHIPDATE < '1995-10-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE6
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE6)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE6;

---

CREATE VIEW REVENUE7 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-06-01'
		AND L_SHIPDATE < '1996-09-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE7
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE7)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE7;

---

CREATE VIEW REVENUE8 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-07-01'
		AND L_SHIPDATE < '1997-10-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE8
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE8)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE8;

---

CREATE VIEW REVENUE9 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-08-01'
		AND L_SHIPDATE < '1995-11-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE9
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE9)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE9;

---

CREATE VIEW REVENUE10 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-04-01'
		AND L_SHIPDATE < '1996-07-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE10
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE10)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE10;

---

CREATE VIEW REVENUE11 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-08-01'
		AND L_SHIPDATE < '1994-11-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE11
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE11)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE11;

---

CREATE VIEW REVENUE12 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-08-01'
		AND L_SHIPDATE < '1996-11-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE12
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE12)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE12;

---

CREATE VIEW REVENUE13 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-09-01'
		AND L_SHIPDATE < '1997-12-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE13
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE13)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE13;

---

CREATE VIEW REVENUE14 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-01-01'
		AND L_SHIPDATE < '1994-04-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE14
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE14)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE14;

---

CREATE VIEW REVENUE15 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-08-01'
		AND L_SHIPDATE < '1994-11-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE15
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE15)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE15;

---

CREATE VIEW REVENUE16 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-05-01'
		AND L_SHIPDATE < '1993-08-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE16
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE16)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE16;

---

CREATE VIEW REVENUE17 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-03-01'
		AND L_SHIPDATE < '1993-06-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE17
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE17)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE17;

---

CREATE VIEW REVENUE18 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-01-01'
		AND L_SHIPDATE < '1996-04-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE18
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE18)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE18;

---

CREATE VIEW REVENUE19 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-04-01'
		AND L_SHIPDATE < '1994-07-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE19
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE19)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE19;

---

CREATE VIEW REVENUE20 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-10-01'
		AND L_SHIPDATE < '1996-01-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE20
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE20)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE20;

---

CREATE VIEW REVENUE21 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-01-01'
		AND L_SHIPDATE < '1993-04-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE21
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE21)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE21;

---

CREATE VIEW REVENUE22 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-10-01'
		AND L_SHIPDATE < '1994-01-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE22
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE22)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE22;

---

CREATE VIEW REVENUE23 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-12-01'
		AND L_SHIPDATE < '1994-03-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE23
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE23)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE23;

---

CREATE VIEW REVENUE24 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-05-01'
		AND L_SHIPDATE < '1996-08-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE24
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE24)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE24;

---

CREATE VIEW REVENUE25 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-08-01'
		AND L_SHIPDATE < '1994-11-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE25
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE25)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE25;

---

CREATE VIEW REVENUE26 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-02-01'
		AND L_SHIPDATE < '1997-05-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE26
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE26)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE26;

---

CREATE VIEW REVENUE27 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-01-01'
		AND L_SHIPDATE < '1993-04-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE27
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE27)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE27;

---

CREATE VIEW REVENUE28 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-09-01'
		AND L_SHIPDATE < '1995-12-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE28
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE28)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE28;

---

CREATE VIEW REVENUE29 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-02-01'
		AND L_SHIPDATE < '1997-05-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE29
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE29)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE29;

---

CREATE VIEW REVENUE30 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-04-01'
		AND L_SHIPDATE < '1993-07-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE30
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE30)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE30;

---

CREATE VIEW REVENUE31 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-09-01'
		AND L_SHIPDATE < '1994-12-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE31
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE31)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE31;

---

CREATE VIEW REVENUE32 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-07-01'
		AND L_SHIPDATE < '1997-10-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE32
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE32)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE32;

---

CREATE VIEW REVENUE33 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-11-01'
		AND L_SHIPDATE < '1997-02-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE33
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE33)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE33;

---

CREATE VIEW REVENUE34 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-04-01'
		AND L_SHIPDATE < '1993-07-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE34
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE34)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE34;

---

CREATE VIEW REVENUE35 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-01-01'
		AND L_SHIPDATE < '1994-04-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE35
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE35)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE35;

---

CREATE VIEW REVENUE36 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-09-01'
		AND L_SHIPDATE < '1994-12-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE36
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE36)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE36;

---

CREATE VIEW REVENUE37 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-06-01'
		AND L_SHIPDATE < '1997-09-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE37
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE37)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE37;

---

CREATE VIEW REVENUE38 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-11-01'
		AND L_SHIPDATE < '1996-02-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE38
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE38)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE38;

---

CREATE VIEW REVENUE39 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-07-01'
		AND L_SHIPDATE < '1994-10-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE39
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE39)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE39;

---

CREATE VIEW REVENUE40 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-02-01'
		AND L_SHIPDATE < '1996-05-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE40
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE40)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE40;

---

CREATE VIEW REVENUE41 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-03-01'
		AND L_SHIPDATE < '1997-06-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE41
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE41)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE41;

---

CREATE VIEW REVENUE42 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-08-01'
		AND L_SHIPDATE < '1996-11-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE42
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE42)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE42;

---

CREATE VIEW REVENUE43 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-01-01'
		AND L_SHIPDATE < '1993-04-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE43
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE43)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE43;

---

CREATE VIEW REVENUE44 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-04-01'
		AND L_SHIPDATE < '1996-07-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE44
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE44)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE44;

---

CREATE VIEW REVENUE45 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-12-01'
		AND L_SHIPDATE < '1995-03-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE45
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE45)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE45;

---

CREATE VIEW REVENUE46 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-01-01'
		AND L_SHIPDATE < '1993-04-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE46
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE46)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE46;

---

CREATE VIEW REVENUE47 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-01-01'
		AND L_SHIPDATE < '1996-04-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE47
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE47)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE47;

---

CREATE VIEW REVENUE48 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-11-01'
		AND L_SHIPDATE < '1995-02-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE48
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE48)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE48;

---

CREATE VIEW REVENUE49 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-05-01'
		AND L_SHIPDATE < '1993-08-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE49
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE49)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE49;

---

CREATE VIEW REVENUE50 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-06-01'
		AND L_SHIPDATE < '1995-09-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE50
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE50)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE50;

---

CREATE VIEW REVENUE51 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-07-01'
		AND L_SHIPDATE < '1994-10-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE51
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE51)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE51;

---

CREATE VIEW REVENUE52 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-02-01'
		AND L_SHIPDATE < '1997-05-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE52
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE52)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE52;

---

CREATE VIEW REVENUE53 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-04-01'
		AND L_SHIPDATE < '1993-07-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE53
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE53)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE53;

---

CREATE VIEW REVENUE54 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-02-01'
		AND L_SHIPDATE < '1997-05-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE54
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE54)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE54;

---

CREATE VIEW REVENUE55 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-10-01'
		AND L_SHIPDATE < '1995-01-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE55
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE55)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE55;

---

CREATE VIEW REVENUE56 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-09-01'
		AND L_SHIPDATE < '1996-12-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE56
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE56)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE56;

---

CREATE VIEW REVENUE57 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-06-01'
		AND L_SHIPDATE < '1994-09-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE57
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE57)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE57;

---

CREATE VIEW REVENUE58 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-07-01'
		AND L_SHIPDATE < '1994-10-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE58
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE58)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE58;

---

CREATE VIEW REVENUE59 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-10-01'
		AND L_SHIPDATE < '1998-01-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE59
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE59)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE59;

---

CREATE VIEW REVENUE60 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-06-01'
		AND L_SHIPDATE < '1993-09-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE60
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE60)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE60;

---

CREATE VIEW REVENUE61 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-05-01'
		AND L_SHIPDATE < '1996-08-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE61
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE61)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE61;

---

CREATE VIEW REVENUE62 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-11-01'
		AND L_SHIPDATE < '1997-02-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE62
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE62)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE62;

---

CREATE VIEW REVENUE63 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-09-01'
		AND L_SHIPDATE < '1993-12-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE63
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE63)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE63;

---

CREATE VIEW REVENUE64 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-07-01'
		AND L_SHIPDATE < '1995-10-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE64
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE64)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE64;

---

CREATE VIEW REVENUE65 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-10-01'
		AND L_SHIPDATE < '1996-01-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE65
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE65)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE65;

---

CREATE VIEW REVENUE66 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-12-01'
		AND L_SHIPDATE < '1996-03-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE66
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE66)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE66;

---

CREATE VIEW REVENUE67 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-08-01'
		AND L_SHIPDATE < '1996-11-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE67
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE67)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE67;

---

CREATE VIEW REVENUE68 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-01-01'
		AND L_SHIPDATE < '1997-04-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE68
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE68)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE68;

---

CREATE VIEW REVENUE69 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-06-01'
		AND L_SHIPDATE < '1997-09-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE69
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE69)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE69;

---

CREATE VIEW REVENUE70 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-01-01'
		AND L_SHIPDATE < '1997-04-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE70
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE70)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE70;

---

CREATE VIEW REVENUE71 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-03-01'
		AND L_SHIPDATE < '1995-06-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE71
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE71)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE71;

---

CREATE VIEW REVENUE72 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-02-01'
		AND L_SHIPDATE < '1997-05-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE72
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE72)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE72;

---

CREATE VIEW REVENUE73 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-04-01'
		AND L_SHIPDATE < '1993-07-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE73
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE73)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE73;

---

CREATE VIEW REVENUE74 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-03-01'
		AND L_SHIPDATE < '1995-06-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE74
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE74)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE74;

---

CREATE VIEW REVENUE75 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-10-01'
		AND L_SHIPDATE < '1995-01-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE75
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE75)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE75;

---

CREATE VIEW REVENUE76 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-06-01'
		AND L_SHIPDATE < '1996-09-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE76
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE76)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE76;

---

CREATE VIEW REVENUE77 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-03-01'
		AND L_SHIPDATE < '1996-06-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE77
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE77)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE77;

---

CREATE VIEW REVENUE78 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-11-01'
		AND L_SHIPDATE < '1995-02-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE78
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE78)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE78;

---

CREATE VIEW REVENUE79 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-12-01'
		AND L_SHIPDATE < '1994-03-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE79
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE79)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE79;

---

CREATE VIEW REVENUE80 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-05-01'
		AND L_SHIPDATE < '1995-08-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE80
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE80)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE80;

---

CREATE VIEW REVENUE81 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-04-01'
		AND L_SHIPDATE < '1995-07-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE81
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE81)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE81;

---

CREATE VIEW REVENUE82 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-03-01'
		AND L_SHIPDATE < '1996-06-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE82
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE82)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE82;

---

CREATE VIEW REVENUE83 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-07-01'
		AND L_SHIPDATE < '1994-10-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE83
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE83)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE83;

---

CREATE VIEW REVENUE84 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-03-01'
		AND L_SHIPDATE < '1995-06-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE84
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE84)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE84;

---

CREATE VIEW REVENUE85 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-08-01'
		AND L_SHIPDATE < '1997-11-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE85
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE85)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE85;

---

CREATE VIEW REVENUE86 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-11-01'
		AND L_SHIPDATE < '1994-02-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE86
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE86)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE86;

---

CREATE VIEW REVENUE87 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-03-01'
		AND L_SHIPDATE < '1993-06-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE87
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE87)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE87;

---

CREATE VIEW REVENUE88 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-07-01'
		AND L_SHIPDATE < '1994-10-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE88
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE88)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE88;

---

CREATE VIEW REVENUE89 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-07-01'
		AND L_SHIPDATE < '1997-10-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE89
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE89)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE89;

---

CREATE VIEW REVENUE90 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-12-01'
		AND L_SHIPDATE < '1995-03-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE90
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE90)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE90;

---

CREATE VIEW REVENUE91 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-09-01'
		AND L_SHIPDATE < '1996-12-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE91
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE91)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE91;

---

CREATE VIEW REVENUE92 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1993-06-01'
		AND L_SHIPDATE < '1993-09-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE92
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE92)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE92;

---

CREATE VIEW REVENUE93 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1995-11-01'
		AND L_SHIPDATE < '1996-02-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE93
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE93)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE93;

---

CREATE VIEW REVENUE94 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-10-01'
		AND L_SHIPDATE < '1997-01-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE94
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE94)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE94;

---

CREATE VIEW REVENUE95 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1997-10-01'
		AND L_SHIPDATE < '1998-01-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE95
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE95)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE95;

---

CREATE VIEW REVENUE96 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-03-01'
		AND L_SHIPDATE < '1994-06-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE96
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE96)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE96;

---

CREATE VIEW REVENUE97 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1996-08-01'
		AND L_SHIPDATE < '1996-11-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE97
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE97)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE97;

---

CREATE VIEW REVENUE98 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-09-01'
		AND L_SHIPDATE < '1994-12-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE98
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE98)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE98;

---

CREATE VIEW REVENUE99 (SUPPLIER_NO, TOTAL_REVENUE) AS
SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
FROM LINEITEM
WHERE L_SHIPDATE >= '1994-11-01'
		AND L_SHIPDATE < '1995-02-01'
GROUP BY L_SUPPKEY;

SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE
FROM SUPPLIER, REVENUE99
WHERE S_SUPPKEY = SUPPLIER_NO
		AND TOTAL_REVENUE =
				(SELECT MAX(TOTAL_REVENUE)
					FROM REVENUE99)
ORDER BY S_SUPPKEY;

DROP VIEW REVENUE99;
