SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#51'
		AND P_TYPE not like 'LARGE PLATED%'
		AND P_SIZE IN (36, 27, 47, 42, 41, 34, 50, 48)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#32'
		AND P_TYPE not like 'SMALL ANODIZED%'
		AND P_SIZE IN (12, 47, 13, 19, 3, 16, 28, 35)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#35'
		AND P_TYPE not like 'ECONOMY PLATED%'
		AND P_SIZE IN (27, 33, 36, 39, 20, 21, 8, 5)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#31'
		AND P_TYPE not like 'PROMO POLISHED%'
		AND P_SIZE IN (1, 16, 31, 46, 5, 38, 14, 20)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#43'
		AND P_TYPE not like 'STANDARD PLATED%'
		AND P_SIZE IN (47, 4, 1, 19, 12, 37, 40, 21)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#13'
		AND P_TYPE not like 'MEDIUM POLISHED%'
		AND P_SIZE IN (49, 22, 19, 21, 37, 36, 25, 41)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#14'
		AND P_TYPE not like 'MEDIUM POLISHED%'
		AND P_SIZE IN (18, 21, 6, 33, 26, 17, 41, 50)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#24'
		AND P_TYPE not like 'MEDIUM ANODIZED%'
		AND P_SIZE IN (11, 5, 31, 9, 23, 22, 44, 16)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#44'
		AND P_TYPE not like 'STANDARD BURNISHED%'
		AND P_SIZE IN (15, 22, 12, 39, 1, 13, 28, 36)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#12'
		AND P_TYPE not like 'STANDARD PLATED%'
		AND P_SIZE IN (44, 20, 48, 11, 13, 23, 50, 30)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#53'
		AND P_TYPE not like 'LARGE BURNISHED%'
		AND P_SIZE IN (45, 39, 46, 47, 25, 34, 37, 17)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#23'
		AND P_TYPE not like 'ECONOMY BRUSHED%'
		AND P_SIZE IN (41, 24, 29, 23, 44, 2, 8, 36)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#51'
		AND P_TYPE not like 'SMALL PLATED%'
		AND P_SIZE IN (10, 3, 32, 36, 18, 13, 27, 17)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#13'
		AND P_TYPE not like 'STANDARD ANODIZED%'
		AND P_SIZE IN (26, 16, 3, 44, 14, 40, 31, 29)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#35'
		AND P_TYPE not like 'PROMO PLATED%'
		AND P_SIZE IN (40, 33, 45, 23, 32, 12, 36, 24)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#15'
		AND P_TYPE not like 'LARGE PLATED%'
		AND P_SIZE IN (21, 5, 26, 30, 22, 41, 11, 25)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#25'
		AND P_TYPE not like 'STANDARD PLATED%'
		AND P_SIZE IN (14, 18, 4, 47, 5, 7, 21, 9)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#25'
		AND P_TYPE not like 'LARGE BRUSHED%'
		AND P_SIZE IN (28, 42, 34, 23, 46, 35, 19, 12)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#42'
		AND P_TYPE not like 'SMALL ANODIZED%'
		AND P_SIZE IN (47, 43, 35, 50, 18, 1, 6, 15)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#35'
		AND P_TYPE not like 'SMALL BRUSHED%'
		AND P_SIZE IN (48, 6, 29, 15, 28, 40, 35, 24)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#45'
		AND P_TYPE not like 'PROMO BURNISHED%'
		AND P_SIZE IN (16, 12, 5, 35, 18, 37, 32, 4)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#41'
		AND P_TYPE not like 'PROMO BRUSHED%'
		AND P_SIZE IN (18, 15, 14, 35, 26, 13, 34, 16)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#15'
		AND P_TYPE not like 'LARGE PLATED%'
		AND P_SIZE IN (11, 22, 3, 41, 34, 26, 16, 2)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#34'
		AND P_TYPE not like 'MEDIUM PLATED%'
		AND P_SIZE IN (24, 8, 1, 31, 32, 14, 45, 6)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#52'
		AND P_TYPE not like 'SMALL ANODIZED%'
		AND P_SIZE IN (3, 38, 13, 18, 22, 28, 9, 48)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#35'
		AND P_TYPE not like 'SMALL ANODIZED%'
		AND P_SIZE IN (17, 8, 45, 42, 31, 30, 3, 32)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#21'
		AND P_TYPE not like 'ECONOMY PLATED%'
		AND P_SIZE IN (2, 29, 44, 17, 15, 32, 6, 30)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#25'
		AND P_TYPE not like 'PROMO BURNISHED%'
		AND P_SIZE IN (3, 7, 35, 44, 4, 48, 49, 11)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#55'
		AND P_TYPE not like 'STANDARD BRUSHED%'
		AND P_SIZE IN (11, 29, 23, 12, 5, 42, 16, 45)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#34'
		AND P_TYPE not like 'LARGE ANODIZED%'
		AND P_SIZE IN (41, 43, 28, 2, 38, 19, 5, 47)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#32'
		AND P_TYPE not like 'SMALL POLISHED%'
		AND P_SIZE IN (34, 42, 45, 37, 31, 23, 3, 14)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#44'
		AND P_TYPE not like 'LARGE BRUSHED%'
		AND P_SIZE IN (30, 38, 25, 20, 17, 5, 3, 44)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#14'
		AND P_TYPE not like 'PROMO POLISHED%'
		AND P_SIZE IN (14, 33, 41, 5, 15, 50, 17, 13)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#34'
		AND P_TYPE not like 'PROMO ANODIZED%'
		AND P_SIZE IN (19, 39, 32, 22, 40, 17, 36, 8)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#14'
		AND P_TYPE not like 'LARGE BRUSHED%'
		AND P_SIZE IN (39, 12, 38, 22, 34, 24, 16, 6)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#54'
		AND P_TYPE not like 'SMALL BRUSHED%'
		AND P_SIZE IN (12, 26, 49, 45, 5, 15, 38, 10)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#44'
		AND P_TYPE not like 'PROMO PLATED%'
		AND P_SIZE IN (47, 29, 10, 16, 5, 25, 6, 2)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#51'
		AND P_TYPE not like 'SMALL POLISHED%'
		AND P_SIZE IN (22, 29, 8, 15, 26, 12, 39, 3)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#12'
		AND P_TYPE not like 'STANDARD POLISHED%'
		AND P_SIZE IN (27, 44, 30, 33, 24, 22, 14, 45)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#14'
		AND P_TYPE not like 'MEDIUM BURNISHED%'
		AND P_SIZE IN (14, 38, 25, 15, 3, 32, 37, 31)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#52'
		AND P_TYPE not like 'MEDIUM BRUSHED%'
		AND P_SIZE IN (41, 28, 35, 48, 15, 19, 11, 34)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#43'
		AND P_TYPE not like 'STANDARD ANODIZED%'
		AND P_SIZE IN (31, 5, 30, 14, 10, 38, 4, 45)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#33'
		AND P_TYPE not like 'MEDIUM POLISHED%'
		AND P_SIZE IN (20, 31, 3, 37, 30, 18, 41, 40)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#53'
		AND P_TYPE not like 'STANDARD ANODIZED%'
		AND P_SIZE IN (44, 15, 28, 48, 10, 21, 4, 22)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#41'
		AND P_TYPE not like 'ECONOMY ANODIZED%'
		AND P_SIZE IN (4, 45, 13, 46, 6, 37, 15, 43)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#45'
		AND P_TYPE not like 'MEDIUM BURNISHED%'
		AND P_SIZE IN (33, 37, 40, 14, 20, 13, 31, 1)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#52'
		AND P_TYPE not like 'SMALL POLISHED%'
		AND P_SIZE IN (46, 39, 41, 16, 44, 28, 40, 36)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#42'
		AND P_TYPE not like 'MEDIUM ANODIZED%'
		AND P_SIZE IN (22, 47, 41, 50, 44, 38, 31, 39)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#21'
		AND P_TYPE not like 'LARGE BRUSHED%'
		AND P_SIZE IN (17, 8, 46, 20, 1, 10, 45, 49)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#35'
		AND P_TYPE not like 'ECONOMY ANODIZED%'
		AND P_SIZE IN (29, 38, 3, 7, 21, 26, 13, 33)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#41'
		AND P_TYPE not like 'SMALL POLISHED%'
		AND P_SIZE IN (6, 10, 14, 41, 22, 8, 16, 31)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#23'
		AND P_TYPE not like 'LARGE BURNISHED%'
		AND P_SIZE IN (24, 44, 4, 50, 48, 33, 19, 23)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#21'
		AND P_TYPE not like 'STANDARD BRUSHED%'
		AND P_SIZE IN (37, 9, 44, 12, 21, 27, 41, 38)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;

---

SELECT P_BRAND, P_TYPE, P_SIZE, COUNT(DISTINCT PS_SUPPKEY) AS SUPPLIER_CNT
FROM PARTSUPP, PART
WHERE P_PARTKEY = PS_PARTKEY
		AND P_BRAND <> 'Brand#22'
		AND P_TYPE not like 'MEDIUM ANODIZED%'
		AND P_SIZE IN (49, 41, 1, 40, 33, 10, 47, 6)
		AND PS_SUPPKEY NOT IN
				(SELECT S_SUPPKEY
					FROM SUPPLIER
					WHERE S_COMMENT like '%Customer%Complaints%')
GROUP BY P_BRAND, P_TYPE, P_SIZE
ORDER BY SUPPLIER_CNT DESC, P_BRAND, P_TYPE, P_SIZE;
