SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'ghost%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'PERU'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'seashell%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'smoke%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ALGERIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'black%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'VIETNAM'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'chocolate%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'black%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'ivory%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'KENYA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'brown%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED KINGDOM'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'snow%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'BRAZIL'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'wheat%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JAPAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'khaki%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDONESIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'maroon%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ARGENTINA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'rosy%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED KINGDOM'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'puff%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOROCCO'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'khaki%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'deep%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CHINA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'drab%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'goldenrod%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'medium%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOROCCO'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'bisque%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JORDAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'drab%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDONESIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'mint%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'PERU'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'navajo%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'BRAZIL'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'powder%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'RUSSIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'cream%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'BRAZIL'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'turquoise%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'BRAZIL'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'powder%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'PERU'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'dodger%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'cyan%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'indian%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'ghost%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JORDAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'royal%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'lemon%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ARGENTINA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'navy%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JORDAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'yellow%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOZAMBIQUE'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'beige%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'grey%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'RUSSIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'lace%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'misty%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'royal%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'tan%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JORDAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'blush%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'GERMANY'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'peach%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOZAMBIQUE'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'cream%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'RUSSIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'firebrick%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'sandy%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOROCCO'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'hot%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAQ'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'purple%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED STATES'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'salmon%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'olive%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'coral%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOZAMBIQUE'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'wheat%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDONESIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'maroon%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'mint%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CHINA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'tan%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JAPAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'papaya%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'wheat%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOZAMBIQUE'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'dim%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'VIETNAM'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'blue%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'almond%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDONESIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'sky%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JORDAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'midnight%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'PERU'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'orchid%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'RUSSIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'green%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOROCCO'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'cornflower%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOZAMBIQUE'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'chocolate%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'floral%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CANADA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'dodger%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOZAMBIQUE'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'smoke%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CHINA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'deep%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED KINGDOM'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'dim%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'sienna%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED KINGDOM'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'orange%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'BRAZIL'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'moccasin%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JORDAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'grey%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CANADA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'saddle%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'maroon%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'metallic%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'PERU'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'antique%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAN'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'plum%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'navajo%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'medium%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ETHIOPIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'navajo%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ALGERIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'spring%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDONESIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'royal%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CHINA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'salmon%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ALGERIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'saddle%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'firebrick%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1994-01-01'
												AND L_SHIPDATE < '1995-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'dark%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'gainsboro%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOZAMBIQUE'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'drab%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1996-01-01'
												AND L_SHIPDATE < '1997-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOZAMBIQUE'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'grey%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'tomato%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1993-01-01'
												AND L_SHIPDATE < '1994-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'turquoise%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'VIETNAM'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'lavender%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'FRANCE'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'chocolate%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1995-01-01'
												AND L_SHIPDATE < '1996-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'RUSSIA'
ORDER BY S_NAME;

---

SELECT S_NAME, S_ADDRESS
FROM SUPPLIER, NATION
WHERE S_SUPPKEY IN
				(SELECT PS_SUPPKEY
					FROM PARTSUPP
					WHERE PS_PARTKEY IN
									(SELECT P_PARTKEY
										FROM PART
										WHERE P_NAME like 'plum%')
							AND PS_AVAILQTY >
									(SELECT 0.5 * SUM(L_QUANTITY)
										FROM LINEITEM
										WHERE L_PARTKEY = PS_PARTKEY
												AND L_SUPPKEY = PS_SUPPKEY
												AND L_SHIPDATE >= '1997-01-01'
												AND L_SHIPDATE < '1998-01-01'))
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDONESIA'
ORDER BY S_NAME;
