SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'MOZAMBIQUE' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM POLISHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'KENYA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD BRUSHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'FRANCE' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY POLISHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'IRAQ' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY BRUSHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'VIETNAM' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO POLISHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ROMANIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY PLATED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'FRANCE' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY BRUSHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ARGENTINA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM ANODIZED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ETHIOPIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD ANODIZED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'PERU' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE ANODIZED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'GERMANY' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL ANODIZED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'IRAQ' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE PLATED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'CANADA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL BRUSHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'VIETNAM' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL POLISHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'FRANCE' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL POLISHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'GERMANY' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE BRUSHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'CANADA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY POLISHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ALGERIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY POLISHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'CHINA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE BURNISHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'INDONESIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL BURNISHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'BRAZIL' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE PLATED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'KENYA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM POLISHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'JORDAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE BURNISHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'MOZAMBIQUE' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY BURNISHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'IRAQ' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY POLISHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'INDIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL POLISHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'MOROCCO' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE BURNISHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ROMANIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO BRUSHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'FRANCE' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD BURNISHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;
