SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1994-01-01'
		AND L_RECEIPTDATE < '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'RAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('FOB', 'REG AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'REG AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1996-01-01'
		AND L_RECEIPTDATE < '1997-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('RAIL', 'FOB')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1994-01-01'
		AND L_RECEIPTDATE < '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('RAIL', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('SHIP', 'RAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1994-01-01'
		AND L_RECEIPTDATE < '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('FOB', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1996-01-01'
		AND L_RECEIPTDATE < '1997-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('RAIL', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('SHIP', 'FOB')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('TRUCK', 'REG AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('TRUCK', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('TRUCK', 'REG AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'RAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1996-01-01'
		AND L_RECEIPTDATE < '1997-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('SHIP', 'TRUCK')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('TRUCK', 'REG AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('TRUCK', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1994-01-01'
		AND L_RECEIPTDATE < '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('TRUCK', 'REG AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1996-01-01'
		AND L_RECEIPTDATE < '1997-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('SHIP', 'REG AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1994-01-01'
		AND L_RECEIPTDATE < '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1994-01-01'
		AND L_RECEIPTDATE < '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('RAIL', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('FOB', 'RAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('TRUCK', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('SHIP', 'TRUCK')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('FOB', 'RAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('MAIL', 'REG AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1996-01-01'
		AND L_RECEIPTDATE < '1997-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('TRUCK', 'RAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1996-01-01'
		AND L_RECEIPTDATE < '1997-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('RAIL', 'REG AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('SHIP', 'FOB')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('SHIP', 'TRUCK')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('RAIL', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('FOB', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1994-01-01'
		AND L_RECEIPTDATE < '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'TRUCK')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('TRUCK', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1994-01-01'
		AND L_RECEIPTDATE < '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('MAIL', 'TRUCK')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('SHIP', 'FOB')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('MAIL', 'TRUCK')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('SHIP', 'TRUCK')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1996-01-01'
		AND L_RECEIPTDATE < '1997-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('RAIL', 'REG AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'FOB')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1996-01-01'
		AND L_RECEIPTDATE < '1997-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('MAIL', 'AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1996-01-01'
		AND L_RECEIPTDATE < '1997-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('FOB', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('MAIL', 'AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('TRUCK', 'FOB')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1996-01-01'
		AND L_RECEIPTDATE < '1997-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'RAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('TRUCK', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1996-01-01'
		AND L_RECEIPTDATE < '1997-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('FOB', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('RAIL', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'FOB')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1994-01-01'
		AND L_RECEIPTDATE < '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'RAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'REG AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1996-01-01'
		AND L_RECEIPTDATE < '1997-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('SHIP', 'REG AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('MAIL', 'TRUCK')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('SHIP', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('RAIL', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'TRUCK')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1994-01-01'
		AND L_RECEIPTDATE < '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('RAIL', 'TRUCK')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('TRUCK', 'RAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('SHIP', 'REG AIR')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1994-01-01'
		AND L_RECEIPTDATE < '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('RAIL', 'FOB')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('FOB', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1994-01-01'
		AND L_RECEIPTDATE < '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('MAIL', 'TRUCK')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('MAIL', 'FOB')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'SHIP')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1997-01-01'
		AND L_RECEIPTDATE < '1998-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('REG AIR', 'FOB')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('SHIP', 'RAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1995-01-01'
		AND L_RECEIPTDATE < '1996-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'RAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('AIR', 'FOB')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1994-01-01'
		AND L_RECEIPTDATE < '1995-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;

---

SELECT L_SHIPMODE,
	SUM(CASE
									WHEN O_ORDERPRIORITY = '1-URGENT'
														OR O_ORDERPRIORITY = '2-HIGH' THEN 1
									ELSE 0
					END) AS HIGH_LINE_COUNT,
	SUM(CASE
									WHEN O_ORDERPRIORITY <> '1-URGENT'
														AND O_ORDERPRIORITY <> '2-HIGH' THEN 1
									ELSE 0
					END) AS LOW_LINE_COUNT
FROM ORDERS, LINEITEM
WHERE O_ORDERKEY = L_ORDERKEY
		AND L_SHIPMODE IN ('TRUCK', 'MAIL')
		AND L_COMMITDATE < L_RECEIPTDATE
		AND L_SHIPDATE < L_COMMITDATE
		AND L_RECEIPTDATE >= '1993-01-01'
		AND L_RECEIPTDATE < '1994-01-01'
GROUP BY L_SHIPMODE
ORDER BY L_SHIPMODE;
