SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%smoke%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%antique%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%rosy%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%lime%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%medium%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%tomato%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%turquoise%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%black%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%lemon%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%yellow%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%navy%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%violet%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%snow%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%orange%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%lemon%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%azure%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;
