SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%special%deposits%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%pending%accounts%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%pending%packages%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%express%deposits%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%special%deposits%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%special%deposits%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%pending%deposits%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%special%packages%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%special%requests%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%express%accounts%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%pending%accounts%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%pending%accounts%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%unusual%requests%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%unusual%accounts%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%special%requests%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%unusual%requests%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%special%requests%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%unusual%deposits%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%express%packages%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%express%requests%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%pending%requests%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%special%accounts%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%unusual%packages%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%unusual%deposits%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%unusual%deposits%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%unusual%requests%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%pending%deposits%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%special%packages%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%unusual%packages%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%special%accounts%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%special%deposits%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%pending%accounts%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%express%requests%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%pending%requests%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%unusual%requests%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%pending%packages%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%express%accounts%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%express%deposits%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;

---

SELECT C_COUNT, COUNT(*) AS CUSTDIST
FROM
		(SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS C_COUNT
			FROM CUSTOMER
			LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
			AND O_COMMENT not like '%unusual%packages%'
			GROUP BY C_CUSTKEY) AS C_ORDERS
GROUP BY C_COUNT
ORDER BY CUSTDIST DESC, C_COUNT DESC;
