version: "3.5"

services:
  backend:
    image: hyrise/bp1920:cockpit-backend
    build: 
      context: .
      dockerfile: ./hyrisecockpit/Dockerfile
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    
  influxdb:
    image: influxdb:alpine
    ports:
      - "8086:8086"

  frontend:
    image: hyrise/bp1920:cockpit-frontent
    build:
        context: .
        dockerfile: ./hyrisecockpit/frontend/Dockerfile
    env_file:
      - .env.docker
    ports:
      - "5000:5000"

  hyrise_1:
    image: hyrise/bp1920:hyrise
    build: 
      context: .
      dockerfile: ./hyrise/Dockerfile
    ports:
      - "5432:5432"

  hyrise_2:
    image: hyrise/bp1920:hyrise
    build: 
      context: .
      dockerfile: ./hyrise/Dockerfile
    ports:
      - "6432:5432"

  watchtower:
    environment:
      - WATCHTOWER_CLEANUP=1
      - WATCHTOWER_POLL_INTERVAL=1800
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json