version: "3.5"

services:
  backend:
    image: hyrise/bp1920:cockpit-backend
    environment:
      - STORAGE_HOST=influxdb
    ports:
      - "8000:8000"
    
  influxdb:
    image: influxdb:alpine
    ports:
      - "8086:8086"

  frontend:
    image: hyrise/bp1920:cockpit-frontent
    environment:
      - VUE_APP_BACKEND_HOST="127.0.0.1"
    ports:
      - "5000:5000"

  hyrise_1:
    image: hyrise/bp1920:hyrise
    ports:
      - "5432:5432"

  hyrise_2:
    image: hyrise/bp1920:hyrise
    ports:
      - "6432:5432"

  watchtower:
    environment:
      - WATCHTOWER_CLEANUP=1
      - WATCHTOWER_POLL_INTERVAL=1800
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json