version: "3.5"

services:
  backend:
    image: hyrise/bp1920:cockpit-backend
    environment:
      - STORAGE_HOST=influxdb
    ports:
      - "8000:8000"
    
  influxdb:
    image: influxdb:alpine
    ports:
      - "8086:8086"

  frontend:
    image: hyrise/bp1920:cockpit-frontent
    ports:
      - "5000:5000"

  hyrise_1:
    image: hyrise/bp1920:hyrise
    ports:
      - "5432:5432"

  hyrise_2:
    image: hyrise/bp1920:hyrise
    ports:
      - "6432:5432"