version: "3.5"

services:
  backend:
    build: .
    image: udopigorsch/hyrise:buster
    working_dir: /usr/local/Cockpit
    command: "cockpit-backend"
    volumes:
      - .:/usr/local/Cockpit
    ports:
      - "8000:8000"

  manager:
    image: udopigorsch/hyrise:buster
    working_dir: /usr/local/Cockpit
    command: "cockpit-manager"
    volumes:
      - .:/usr/local/Cockpit
    ports:
      - "8001:8001"

  generator:
    image: udopigorsch/hyrise:buster
    working_dir: /usr/local/Cockpit
    command: "cockpit-generator"
    volumes:
      - .:/usr/local/Cockpit
    ports:
      - "8002:8002"
      - "8003:8003"
      
  influxdb:
    image: influxdb:alpine
    volumes:
      - /tmp/cockpit/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  
  hyrise:
    image: udopigorsch/hyrise:hyrise_19.10
    working_dir: "/usr/local/hyrise"
    command: "cmake-build-release/hyriseServer"
    volumes:
      - ./cached_tables:/usr/local/hyrise/cached_tables
    ports:
      - "5432:5432"