version: "3.5"

services:
  backend:
    image: cockpit:3.8.2
    build: .
    working_dir: /usr/local/Cockpit
    command: "cockpit-backend"
    volumes:
      - .:/usr/local/Cockpit
    ports:
      - "8000:8000"

  manager:
    image: cockpit:3.8.2
    working_dir: /usr/local/Cockpit
    command: "cockpit-manager"
    volumes:
      - .:/usr/local/Cockpit
    ports:
      - "8001:8001"

  generator:
    image: cockpit:3.8.2
    working_dir: /usr/local/Cockpit
    command: "cockpit-generator"
    volumes:
      - .:/usr/local/Cockpit
    ports:
      - "8002:8002"
      - "8003:8003"
      
  influxdb:
    image: influxdb:alpine
    volumes:
      - /tmp/cockpit/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"

  frontend:
    image: frontend:buster
    build:
        context: .
        dockerfile: ./hyrisecockpit/frontend/Dockerfile
    command: "npm run serve"
    volumes:
      - ./hyrisecockpit/frontend:/usr/local/Cockpit/hyrisecockpit/frontend
    ports:
      - "8080:8080"
  
  hyrise:
    image: hyrise:bensk1_multithreaded
    build: 
      context: .
      dockerfile: ./hyrise/Dockerfile
    working_dir: "/usr/local/hyrise/cmake-build-release"
    command: "./hyriseServer"
    volumes:
      - ./cached_tables:/usr/local/hyrise/cached_tables
    ports:
      - "5432:5432"