version: "3.5"

services:
  backend:
    image: cockpit-backend:3.8.2
    build: 
      context: .
      dockerfile: ./hyrisecockpit/api/Dockerfile
    command: "cockpit-backend"
    volumes:
      - .:/usr/local/Cockpit

  manager:
    image: cockpit-manager:3.8.2
    build: 
      context: .
      dockerfile: ./hyrisecockpit/database_manager/Dockerfile
    command: "cockpit-manager"
    volumes:
      - .:/usr/local/Cockpit
    
  generator:
    image: cockpit-generator:3.8.2
    build: 
      context: .
      dockerfile: ./hyrisecockpit/workload_generator/Dockerfile
    command: "cockpit-generator"
    volumes:
      - .:/usr/local/Cockpit
          
  influxdb:
    image: influxdb:alpine
    ports:
      - "8086:8086"

  frontend:
    image: frontend:buster
    build:
        context: .
        dockerfile: ./hyrisecockpit/frontend/Dockerfile
    working_dir: "/usr/local/Cockpit/hyrisecockpit/frontend"
    command: "npm run deploy"
  
  hyrise:
    image: hyrise:bensk1_multithreaded
    build: 
      context: .
      dockerfile: ./hyrise/Dockerfile
    working_dir: "/usr/local/hyrise/cmake-build-release"
    command: "./hyriseServer"
    volumes:
      - ./cached_tables:/usr/local/hyrise/cached_tables
    ports:
      - "5432:5432"