version: "3.5"

services:
  backend:
    image: cockpit-backend:3.8.5
    build: 
      context: .
      dockerfile: ./hyrisecockpit/Dockerfile
    ports:
      - "8000:8000"
    
  influxdb:
    image: influxdb:alpine
    ports:
      - "8086:8086"

  frontend:
    image: frontend:buster
    build:
        context: .
        dockerfile: ./hyrisecockpit/frontend/Dockerfile
    ports:
      - "5000:5000"

  hyrise_a:
    image: hyrise:bp1920
    build: 
      context: .
      dockerfile: ./hyrise/Dockerfile
    ports:
      - "5432:5432"

  # hyrise_b:
  #   image: hyrise:bp1920
  #   build: 
  #     context: .
  #     dockerfile: ./hyrise/Dockerfile
  #   ports:
  #     - "6432:5432"