version: "3.5"

services:
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   networks:
  #     - "front"

  backend:
    image: cockpit-backend:3.8.2
    build: 
      context: .
      dockerfile: ./hyrisecockpit/api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - "front"
      - "back"
    environment:
      - VIRTUAL_HOST=swagger-%{COMPOSE_PROJECT_NAME}.local

  manager:
    image: cockpit-manager:3.8.2
    build: 
      context: .
      dockerfile: ./hyrisecockpit/database_manager/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - "back"

  generator:
    image: cockpit-generator:3.8.2
    build: 
      context: .
      dockerfile: ./hyrisecockpit/workload_generator/Dockerfile
    ports:
      - "8002:8002"
      - "8003:8003"
    networks:
      - "back"

  influxdb:
    image: influxdb:alpine
    ports:
      - "8086:8086"
    networks:
      - "back"

  frontend:
    image: frontend:buster
    build:
        context: .
        dockerfile: ./hyrisecockpit/frontend/Dockerfile
    networks:
      - "front"
    ports:
      - "5000:5000"
    environment:
      - VIRTUAL_HOST=cockpit-%{COMPOSE_PROJECT_NAME}.local

  hyrise:
    image: hyrise:bensk1_multithreaded
    build: 
      context: .
      dockerfile: ./hyrise/Dockerfile
    volumes:
      - ./cached_tables:/usr/local/hyrise/cached_tables
    ports:
      - "5432:5432"
    networks:
      - "back"

networks:
  front:
    external:
      name: front
  back:
    driver: bridge