# https://github.com/hyrise/hyrise/wiki/Docker-Image
FROM hyrise/opossum-ci:19.10
LABEL maintainer="upigorsch@me.com"
ENV OPOSSUM_HEADLESS_SETUP=true

# From now on, we're doing additional stuff that would be done manually otherwise
RUN apt-get update
RUN cd /usr/local/ \
    && git clone https://github.com/hyrise/hyrise.git hyrise-git \ 
    && cd hyrise-git \
    && git checkout bp1920 \
    && sed -i 's/-march=native/-march=core2/g' CMakeLists.txt \
    && ./install_dependencies.sh \
    && mkdir /usr/local/hyrise-git/cmake-build-release \
    && cd /usr/local/hyrise-git/cmake-build-release \
    && CXXFLAGS=-fdiagnostics-color=always cmake -DENABLE_NUMA_SUPPORT=Off -DCMAKE_BUILD_TYPE=Release .. \
    && make hyriseConsole hyriseServer \
    && mkdir -p /usr/local/hyrise/lib \
    && cp hyriseServer hyriseConsole /usr/local/hyrise/
RUN cd /usr/local/hyrise-git/cmake-build-release \
    && make CompressionPlugin ClusteringPlugin IndexSelectionPlugin \
    && cp lib/libClusteringPlugin.so lib/libCompressionPlugin.so lib/libIndexSelectionPlugin.so /usr/local/hyrise/lib/ 
ENTRYPOINT ["/usr/local/hyrise/hyriseServer"]
