"""Table names for benchmark tables."""
from typing import Dict, List

table_names: Dict[str, List[str]] = {
    "tpch": [
        "customer",
        "lineitem",
        "nation",
        "orders",
        "part",
        "partsupp",
        "region",
        "supplier",
    ],
    "tpcds": [
        "call_center",
        "catalog_sales",
        "customer_demographics",
        "income_band",
        "promotion",
        "store",
        "time_dim",
        "web_returns",
        "catalog_page",
        "customer_address",
        "date_dim",
        "inventory",
        "reason",
        "store_returns",
        "warehouse",
        "web_sales",
        "catalog_returns",
        "customer",
        "household_demographics",
        "item",
        "ship_mode",
        "store_sales",
        "web_page",
        "web_site",
    ],
    "job": [
        "aka_name",
        "char_name",
        "comp_cast_type",
        "keyword.bin",
        "movie_companies",
        "movie_keyword",
        "person_info",
        "aka_title",
        "company_name",
        "complete_cast",
        "kind_type",
        "movie_info",
        "movie_link",
        "role_type",
        "cast_info",
        "company_type",
        "info_type",
        "link_type",
        "movie_info_idx",
        "name",
        "title",
    ],
    "no-ops": [],
    "mixed": [
        "customer",
        "lineitem",
        "nation",
        "orders",
        "part",
        "partsupp",
        "region",
        "supplier",
    ],
}
