SELECT MIN(CHN.NAME) AS UNCREDITED_VOICED_CHARACTER, MIN(T.TITLE) AS RUSSIAN_MOVIE
FROM CHAR_NAME AS CHN, CAST_INFO AS CI, COMPANY_NAME AS CN, COMPANY_TYPE AS CT, MOVIE_COMPANIES AS MC,
	ROLE_TYPE AS RT, TITLE AS T
WHERE CI.NOTE LIKE '%(voice)%'
		AND CI.NOTE LIKE '%(uncredited)%'
		AND CN.COUNTRY_CODE = '[ru]'
		AND RT.ROLE = 'actor'
		AND T.PRODUCTION_YEAR > 2005
		AND T.ID = MC.MOVIE_ID
		AND T.ID = CI.MOVIE_ID
		AND CI.MOVIE_ID = MC.MOVIE_ID
		AND CHN.ID = CI.PERSON_ROLE_ID
		AND RT.ID = CI.ROLE_ID
		AND CN.ID = MC.COMPANY_ID
		AND CT.ID = MC.COMPANY_TYPE_ID;
