SELECT MIN(CHN.NAME) AS CHARACTER, MIN(T.TITLE) AS MOVIE_WITH_AMERICAN_PRODUCER
FROM CHAR_NAME AS CHN, CAST_INFO AS CI, COMPANY_NAME AS CN, COMPANY_TYPE AS CT, MOVIE_COMPANIES AS MC,
	ROLE_TYPE AS RT, TITLE AS T
WHERE CI.NOTE LIKE '%(producer)%'
		AND CN.COUNTRY_CODE = '[us]'
		AND T.PRODUCTION_YEAR > 1990
		AND T.ID = MC.MOVIE_ID
		AND T.ID = CI.MOVIE_ID
		AND CI.MOVIE_ID = MC.MOVIE_ID
		AND CHN.ID = CI.PERSON_ROLE_ID
		AND RT.ID = CI.ROLE_ID
		AND CN.ID = MC.COMPANY_ID
		AND CT.ID = MC.COMPANY_TYPE_ID;
