SELECT MIN(CN.NAME) AS FROM_COMPANY, MIN(MC.NOTE) AS PRODUCTION_NOTE, MIN(T.TITLE) AS MOVIE_BASED_ON_BOOK
FROM COMPANY_NAME AS CN, COMPANY_TYPE AS CT, KEYWORD AS K, LINK_TYPE AS LT, MOVIE_COMPANIES AS MC,
	MOVIE_KEYWORD AS MK, MOVIE_LINK AS ML, TITLE AS T
WHERE CN.COUNTRY_CODE != '[pl]'
		AND CT.KIND != 'production companies'
		AND CT.KIND IS NOT NULL
		AND K.KEYWORD IN ('sequel', 'revenge', 'based-on-novel')
		AND MC.NOTE IS NOT NULL
		AND T.PRODUCTION_YEAR > 1950
		AND LT.ID = ML.LINK_TYPE_ID
		AND ML.MOVIE_ID = T.ID
		AND T.ID = MK.MOVIE_ID
		AND MK.KEYWORD_ID = K.ID
		AND T.ID = MC.MOVIE_ID
		AND MC.COMPANY_TYPE_ID = CT.ID
		AND MC.COMPANY_ID = CN.ID
		AND ML.MOVIE_ID = MK.MOVIE_ID
		AND ML.MOVIE_ID = MC.MOVIE_ID
		AND MK.MOVIE_ID = MC.MOVIE_ID;
