SELECT MIN(MI.INFO) AS BUDGET, MIN(T.TITLE) AS UNSUCCSESSFUL_MOVIE
FROM COMPANY_NAME AS CN, COMPANY_TYPE AS CT, INFO_TYPE AS IT1, INFO_TYPE AS IT2, MOVIE_COMPANIES AS MC,
	MOVIE_INFO AS MI, MOVIE_INFO_IDX AS MI_IDX, TITLE AS T
WHERE CN.COUNTRY_CODE = '[us]'
		AND CT.KIND IS NOT NULL
		AND (CT.KIND = 'production companies'
							OR CT.KIND = 'distributors')
		AND IT1.INFO = 'budget'
		AND IT2.INFO = 'bottom 10 rank'
		AND T.PRODUCTION_YEAR > 2000
		AND (T.TITLE LIKE 'Birdemic%'
							OR T.TITLE LIKE '%Movie%')
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MI_IDX.MOVIE_ID
		AND MI.INFO_TYPE_ID = IT1.ID
		AND MI_IDX.INFO_TYPE_ID = IT2.ID
		AND T.ID = MC.MOVIE_ID
		AND CT.ID = MC.COMPANY_TYPE_ID
		AND CN.ID = MC.COMPANY_ID
		AND MC.MOVIE_ID = MI.MOVIE_ID
		AND MC.MOVIE_ID = MI_IDX.MOVIE_ID
		AND MI.MOVIE_ID = MI_IDX.MOVIE_ID;
