SELECT MIN(MI_IDX.INFO) AS RATING, MIN(T.TITLE) AS WESTERN_DARK_PRODUCTION
FROM INFO_TYPE AS IT1, INFO_TYPE AS IT2, KEYWORD AS K, KIND_TYPE AS KT, MOVIE_INFO AS MI,
	MOVIE_INFO_IDX AS MI_IDX, MOVIE_KEYWORD AS MK, TITLE AS T
WHERE IT1.INFO = 'countries'
		AND IT2.INFO = 'rating'
		AND K.KEYWORD IN ('murder', 'murder-in-title')
		AND KT.KIND = 'movie'
		AND MI.INFO IN ('Sweden', 'Norway', 'Germany', 'Denmark', 'Swedish', 'Denish', 'Norwegian', 'German',
																			'USA', 'American')
		AND MI_IDX.INFO > '6.0'
		AND T.PRODUCTION_YEAR > 2010
		AND (T.TITLE LIKE '%murder%'
							OR T.TITLE LIKE '%Murder%'
							OR T.TITLE LIKE '%Mord%')
		AND KT.ID = T.KIND_ID
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MK.MOVIE_ID
		AND T.ID = MI_IDX.MOVIE_ID
		AND MK.MOVIE_ID = MI.MOVIE_ID
		AND MK.MOVIE_ID = MI_IDX.MOVIE_ID
		AND MI.MOVIE_ID = MI_IDX.MOVIE_ID
		AND K.ID = MK.KEYWORD_ID
		AND IT1.ID = MI.INFO_TYPE_ID
		AND IT2.ID = MI_IDX.INFO_TYPE_ID;
