SELECT MIN(MI_IDX.INFO) AS RATING, MIN(T.TITLE) AS NORTH_EUROPEAN_DARK_PRODUCTION
FROM INFO_TYPE AS IT1, INFO_TYPE AS IT2, KEYWORD AS K, KIND_TYPE AS KT, MOVIE_INFO AS MI,
	MOVIE_INFO_IDX AS MI_IDX, MOVIE_KEYWORD AS MK, TITLE AS T
WHERE IT1.INFO = 'countries'
		AND IT2.INFO = 'rating'
		AND K.KEYWORD IS NOT NULL
		AND K.KEYWORD IN ('murder', 'murder-in-title', 'blood', 'violence')
		AND KT.KIND IN ('movie', 'episode')
		AND MI.INFO IN ('Sweden', 'Norway', 'Germany', 'Denmark', 'Swedish', 'Danish', 'Norwegian', 'German',
																			'USA', 'American')
		AND MI_IDX.INFO < '8.5'
		AND T.PRODUCTION_YEAR > 2005
		AND KT.ID = T.KIND_ID
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MK.MOVIE_ID
		AND T.ID = MI_IDX.MOVIE_ID
		AND MK.MOVIE_ID = MI.MOVIE_ID
		AND MK.MOVIE_ID = MI_IDX.MOVIE_ID
		AND MI.MOVIE_ID = MI_IDX.MOVIE_ID
		AND K.ID = MK.KEYWORD_ID
		AND IT1.ID = MI.INFO_TYPE_ID
		AND IT2.ID = MI_IDX.INFO_TYPE_ID;
