SELECT MIN(AT.TITLE) AS AKA_TITLE, MIN(T.TITLE) AS INTERNET_MOVIE_TITLE
FROM AKA_TITLE AS AT, COMPANY_NAME AS CN, COMPANY_TYPE AS CT, INFO_TYPE AS IT1, KEYWORD AS K,
	MOVIE_COMPANIES AS MC, MOVIE_INFO AS MI, MOVIE_KEYWORD AS MK, TITLE AS T
WHERE CN.COUNTRY_CODE = '[us]'
		AND IT1.INFO = 'release dates'
		AND MI.NOTE LIKE '%internet%'
		AND T.PRODUCTION_YEAR > 1990
		AND T.ID = AT.MOVIE_ID
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MK.MOVIE_ID
		AND T.ID = MC.MOVIE_ID
		AND MK.MOVIE_ID = MI.MOVIE_ID
		AND MK.MOVIE_ID = MC.MOVIE_ID
		AND MK.MOVIE_ID = AT.MOVIE_ID
		AND MI.MOVIE_ID = MC.MOVIE_ID
		AND MI.MOVIE_ID = AT.MOVIE_ID
		AND MC.MOVIE_ID = AT.MOVIE_ID
		AND K.ID = MK.KEYWORD_ID
		AND IT1.ID = MI.INFO_TYPE_ID
		AND CN.ID = MC.COMPANY_ID
		AND CT.ID = MC.COMPANY_TYPE_ID;
