SELECT MIN(AN.NAME) AS COOL_ACTOR_PSEUDONYM, MIN(T.TITLE) AS SERIES_NAMED_AFTER_CHAR
FROM AKA_NAME AS AN, CAST_INFO AS CI, COMPANY_NAME AS CN, KEYWORD AS K, MOVIE_COMPANIES AS MC,
	MOVIE_KEYWORD AS MK, NAME AS N, TITLE AS T
WHERE CN.COUNTRY_CODE = '[us]'
		AND K.KEYWORD = 'character-name-in-title'
		AND T.EPISODE_NR >= 50
		AND T.EPISODE_NR < 100
		AND AN.PERSON_ID = N.ID
		AND N.ID = CI.PERSON_ID
		AND CI.MOVIE_ID = T.ID
		AND T.ID = MK.MOVIE_ID
		AND MK.KEYWORD_ID = K.ID
		AND T.ID = MC.MOVIE_ID
		AND MC.COMPANY_ID = CN.ID
		AND AN.PERSON_ID = CI.PERSON_ID
		AND CI.MOVIE_ID = MC.MOVIE_ID
		AND CI.MOVIE_ID = MK.MOVIE_ID
		AND MC.MOVIE_ID = MK.MOVIE_ID;
