SELECT MIN(N.NAME) AS MEMBER_IN_CHARNAMED_MOVIE, MIN(N.NAME) AS A1
FROM CAST_INFO AS CI, COMPANY_NAME AS CN, KEYWORD AS K, MOVIE_COMPANIES AS MC, MOVIE_KEYWORD AS MK, NAME AS N,
	TITLE AS T
WHERE K.KEYWORD = 'character-name-in-title'
		AND N.NAME LIKE 'X%'
		AND N.ID = CI.PERSON_ID
		AND CI.MOVIE_ID = T.ID
		AND T.ID = MK.MOVIE_ID
		AND MK.KEYWORD_ID = K.ID
		AND T.ID = MC.MOVIE_ID
		AND MC.COMPANY_ID = CN.ID
		AND CI.MOVIE_ID = MC.MOVIE_ID
		AND CI.MOVIE_ID = MK.MOVIE_ID
		AND MC.MOVIE_ID = MK.MOVIE_ID;
