SELECT MIN(MI.INFO) AS MOVIE_BUDGET, MIN(MI_IDX.INFO) AS MOVIE_VOTES, MIN(T.TITLE) AS MOVIE_TITLE
FROM CAST_INFO AS CI, INFO_TYPE AS IT1, INFO_TYPE AS IT2, MOVIE_INFO AS MI, MOVIE_INFO_IDX AS MI_IDX, NAME AS N,
	TITLE AS T
WHERE CI.NOTE IN ('(writer)', '(head writer)', '(written by)', '(story)', '(story editor)')
		AND IT1.INFO = 'genres'
		AND IT2.INFO = 'rating'
		AND MI.INFO IN ('Horror', 'Thriller')
		AND MI.NOTE IS NULL
		AND MI_IDX.INFO > '8.0'
		AND N.GENDER IS NOT NULL
		AND N.GENDER = 'f'
		AND T.PRODUCTION_YEAR BETWEEN 2008 AND 2014
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MI_IDX.MOVIE_ID
		AND T.ID = CI.MOVIE_ID
		AND CI.MOVIE_ID = MI.MOVIE_ID
		AND CI.MOVIE_ID = MI_IDX.MOVIE_ID
		AND MI.MOVIE_ID = MI_IDX.MOVIE_ID
		AND N.ID = CI.PERSON_ID
		AND IT1.ID = MI.INFO_TYPE_ID
		AND IT2.ID = MI_IDX.INFO_TYPE_ID;
