SELECT MIN(MI.INFO) AS MOVIE_BUDGET, MIN(MI_IDX.INFO) AS MOVIE_VOTES, MIN(T.TITLE) AS MOVIE_TITLE
FROM CAST_INFO AS CI, INFO_TYPE AS IT1, INFO_TYPE AS IT2, MOVIE_INFO AS MI, MOVIE_INFO_IDX AS MI_IDX, NAME AS N,
	TITLE AS T
WHERE CI.NOTE IN ('(writer)', '(head writer)', '(written by)', '(story)', '(story editor)')
		AND IT1.INFO = 'genres'
		AND IT2.INFO = 'votes'
		AND MI.INFO IN ('Horror', 'Action', 'Sci-Fi', 'Thriller', 'Crime', 'War')
		AND N.GENDER = 'm'
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MI_IDX.MOVIE_ID
		AND T.ID = CI.MOVIE_ID
		AND CI.MOVIE_ID = MI.MOVIE_ID
		AND CI.MOVIE_ID = MI_IDX.MOVIE_ID
		AND MI.MOVIE_ID = MI_IDX.MOVIE_ID
		AND N.ID = CI.PERSON_ID
		AND IT1.ID = MI.INFO_TYPE_ID
		AND IT2.ID = MI_IDX.INFO_TYPE_ID;
