SELECT MIN(N.NAME) AS VOICING_ACTRESS, MIN(T.TITLE) AS VOICED_MOVIE
FROM AKA_NAME AS AN, CHAR_NAME AS CHN, CAST_INFO AS CI, COMPANY_NAME AS CN, INFO_TYPE AS IT,
	MOVIE_COMPANIES AS MC, MOVIE_INFO AS MI, NAME AS N, ROLE_TYPE AS RT, TITLE AS T
WHERE CI.NOTE IN ('(voice)', '(voice: Japanese version)', '(voice) (uncredited)',
																			'(voice: English version)')
		AND CN.COUNTRY_CODE = '[us]'
		AND IT.INFO = 'release dates'
		AND MC.NOTE IS NOT NULL
		AND (MC.NOTE LIKE '%(USA)%'
							OR MC.NOTE LIKE '%(worldwide)%')
		AND MI.INFO IS NOT NULL
		AND (MI.INFO LIKE 'Japan:%200%'
							OR MI.INFO LIKE 'USA:%200%')
		AND N.GENDER = 'f'
		AND N.NAME LIKE '%Ang%'
		AND RT.ROLE = 'actress'
		AND T.PRODUCTION_YEAR BETWEEN 2005 AND 2009
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MC.MOVIE_ID
		AND T.ID = CI.MOVIE_ID
		AND MC.MOVIE_ID = CI.MOVIE_ID
		AND MC.MOVIE_ID = MI.MOVIE_ID
		AND MI.MOVIE_ID = CI.MOVIE_ID
		AND CN.ID = MC.COMPANY_ID
		AND IT.ID = MI.INFO_TYPE_ID
		AND N.ID = CI.PERSON_ID
		AND RT.ID = CI.ROLE_ID
		AND N.ID = AN.PERSON_ID
		AND CI.PERSON_ID = AN.PERSON_ID
		AND CHN.ID = CI.PERSON_ROLE_ID;
