SELECT MIN(N.NAME) AS VOICING_ACTRESS, MIN(T.TITLE) AS KUNG_FU_PANDA
FROM AKA_NAME AS AN, CHAR_NAME AS CHN, CAST_INFO AS CI, COMPANY_NAME AS CN, INFO_TYPE AS IT,
	MOVIE_COMPANIES AS MC, MOVIE_INFO AS MI, NAME AS N, ROLE_TYPE AS RT, TITLE AS T
WHERE CI.NOTE = '(voice)'
		AND CN.COUNTRY_CODE = '[us]'
		AND IT.INFO = 'release dates'
		AND MC.NOTE LIKE '%(200%)%'
		AND (MC.NOTE LIKE '%(USA)%'
							OR MC.NOTE LIKE '%(worldwide)%')
		AND MI.INFO IS NOT NULL
		AND (MI.INFO LIKE 'Japan:%2007%'
							OR MI.INFO LIKE 'USA:%2008%')
		AND N.GENDER = 'f'
		AND N.NAME LIKE '%Angel%'
		AND RT.ROLE = 'actress'
		AND T.PRODUCTION_YEAR BETWEEN 2007 AND 2008
		AND T.TITLE LIKE '%Kung%Fu%Panda%'
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MC.MOVIE_ID
		AND T.ID = CI.MOVIE_ID
		AND MC.MOVIE_ID = CI.MOVIE_ID
		AND MC.MOVIE_ID = MI.MOVIE_ID
		AND MI.MOVIE_ID = CI.MOVIE_ID
		AND CN.ID = MC.COMPANY_ID
		AND IT.ID = MI.INFO_TYPE_ID
		AND N.ID = CI.PERSON_ID
		AND RT.ID = CI.ROLE_ID
		AND N.ID = AN.PERSON_ID
		AND CI.PERSON_ID = AN.PERSON_ID
		AND CHN.ID = CI.PERSON_ROLE_ID;
