SELECT MIN(MC.NOTE) AS PRODUCTION_NOTE, MIN(T.TITLE) AS MOVIE_TITLE, MIN(T.PRODUCTION_YEAR) AS MOVIE_YEAR
FROM COMPANY_TYPE AS CT, INFO_TYPE AS IT, MOVIE_COMPANIES AS MC, MOVIE_INFO_IDX AS MI_IDX, TITLE AS T
WHERE CT.KIND = 'production companies'
		AND IT.INFO = 'top 250 rank'
		AND MC.NOTE NOT LIKE '%(as Metro-Goldwyn-Mayer Pictures)%'
		AND (MC.NOTE LIKE '%(co-production)%')
		AND T.PRODUCTION_YEAR > 2010
		AND CT.ID = MC.COMPANY_TYPE_ID
		AND T.ID = MC.MOVIE_ID
		AND T.ID = MI_IDX.MOVIE_ID
		AND MC.MOVIE_ID = MI_IDX.MOVIE_ID
		AND IT.ID = MI_IDX.INFO_TYPE_ID;
