SELECT MIN(CN.NAME) AS MOVIE_COMPANY, MIN(MI_IDX.INFO) AS RATING, MIN(T.TITLE) AS WESTERN_VIOLENT_MOVIE
FROM COMPANY_NAME AS CN, COMPANY_TYPE AS CT, INFO_TYPE AS IT1, INFO_TYPE AS IT2, KEYWORD AS K, KIND_TYPE AS KT,
	MOVIE_COMPANIES AS MC, MOVIE_INFO AS MI, MOVIE_INFO_IDX AS MI_IDX, MOVIE_KEYWORD AS MK, TITLE AS T
WHERE CN.COUNTRY_CODE != '[us]'
		AND IT1.INFO = 'countries'
		AND IT2.INFO = 'rating'
		AND K.KEYWORD IN ('murder', 'murder-in-title', 'blood', 'violence')
		AND KT.KIND IN ('movie', 'episode')
		AND MC.NOTE NOT LIKE '%(USA)%'
		AND MC.NOTE LIKE '%(200%)%'
		AND MI.INFO IN ('Germany', 'German', 'USA', 'American')
		AND MI_IDX.INFO < '7.0'
		AND T.PRODUCTION_YEAR > 2008
		AND KT.ID = T.KIND_ID
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MK.MOVIE_ID
		AND T.ID = MI_IDX.MOVIE_ID
		AND T.ID = MC.MOVIE_ID
		AND MK.MOVIE_ID = MI.MOVIE_ID
		AND MK.MOVIE_ID = MI_IDX.MOVIE_ID
		AND MK.MOVIE_ID = MC.MOVIE_ID
		AND MI.MOVIE_ID = MI_IDX.MOVIE_ID
		AND MI.MOVIE_ID = MC.MOVIE_ID
		AND MC.MOVIE_ID = MI_IDX.MOVIE_ID
		AND K.ID = MK.KEYWORD_ID
		AND IT1.ID = MI.INFO_TYPE_ID
		AND IT2.ID = MI_IDX.INFO_TYPE_ID
		AND CT.ID = MC.COMPANY_TYPE_ID
		AND CN.ID = MC.COMPANY_ID;
