SELECT MIN(KT.KIND) AS MOVIE_KIND, MIN(T.TITLE) AS COMPLETE_US_INTERNET_MOVIE
FROM COMPLETE_CAST AS CC, COMP_CAST_TYPE AS CCT1, COMPANY_NAME AS CN, COMPANY_TYPE AS CT, INFO_TYPE AS IT1,
	KEYWORD AS K, KIND_TYPE AS KT, MOVIE_COMPANIES AS MC, MOVIE_INFO AS MI, MOVIE_KEYWORD AS MK, TITLE AS T
WHERE CCT1.KIND = 'complete+verified'
		AND CN.COUNTRY_CODE = '[us]'
		AND IT1.INFO = 'release dates'
		AND KT.KIND IN ('movie', 'tv movie', 'video movie', 'video game')
		AND MI.NOTE LIKE '%internet%'
		AND MI.INFO IS NOT NULL
		AND (MI.INFO LIKE 'USA:% 199%'
							OR MI.INFO LIKE 'USA:% 200%')
		AND T.PRODUCTION_YEAR > 1990
		AND KT.ID = T.KIND_ID
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MK.MOVIE_ID
		AND T.ID = MC.MOVIE_ID
		AND T.ID = CC.MOVIE_ID
		AND MK.MOVIE_ID = MI.MOVIE_ID
		AND MK.MOVIE_ID = MC.MOVIE_ID
		AND MK.MOVIE_ID = CC.MOVIE_ID
		AND MI.MOVIE_ID = MC.MOVIE_ID
		AND MI.MOVIE_ID = CC.MOVIE_ID
		AND MC.MOVIE_ID = CC.MOVIE_ID
		AND K.ID = MK.KEYWORD_ID
		AND IT1.ID = MI.INFO_TYPE_ID
		AND CN.ID = MC.COMPANY_ID
		AND CT.ID = MC.COMPANY_TYPE_ID
		AND CCT1.ID = CC.STATUS_ID;
