SELECT MIN(CN.NAME) AS PRODUCING_COMPANY, MIN(LT.LINK) AS LINK_TYPE, MIN(T.TITLE) AS COMPLETE_WESTERN_SEQUEL
FROM COMPLETE_CAST AS CC, COMP_CAST_TYPE AS CCT1, COMP_CAST_TYPE AS CCT2, COMPANY_NAME AS CN, COMPANY_TYPE AS CT,
	KEYWORD AS K, LINK_TYPE AS LT, MOVIE_COMPANIES AS MC, MOVIE_INFO AS MI, MOVIE_KEYWORD AS MK,
	MOVIE_LINK AS ML, TITLE AS T
WHERE CCT1.KIND = 'cast'
		AND CCT2.KIND LIKE 'complete%'
		AND CN.COUNTRY_CODE != '[pl]'
		AND (CN.NAME LIKE '%Film%'
							OR CN.NAME LIKE '%Warner%')
		AND CT.KIND = 'production companies'
		AND K.KEYWORD = 'sequel'
		AND LT.LINK LIKE '%follow%'
		AND MC.NOTE IS NULL
		AND MI.INFO IN ('Sweden', 'Norway', 'Germany', 'Denmark', 'Swedish', 'Denish', 'Norwegian', 'German',
																			'English')
		AND T.PRODUCTION_YEAR BETWEEN 1950 AND 2010
		AND LT.ID = ML.LINK_TYPE_ID
		AND ML.MOVIE_ID = T.ID
		AND T.ID = MK.MOVIE_ID
		AND MK.KEYWORD_ID = K.ID
		AND T.ID = MC.MOVIE_ID
		AND MC.COMPANY_TYPE_ID = CT.ID
		AND MC.COMPANY_ID = CN.ID
		AND MI.MOVIE_ID = T.ID
		AND T.ID = CC.MOVIE_ID
		AND CCT1.ID = CC.SUBJECT_ID
		AND CCT2.ID = CC.STATUS_ID
		AND ML.MOVIE_ID = MK.MOVIE_ID
		AND ML.MOVIE_ID = MC.MOVIE_ID
		AND MK.MOVIE_ID = MC.MOVIE_ID
		AND ML.MOVIE_ID = MI.MOVIE_ID
		AND MK.MOVIE_ID = MI.MOVIE_ID
		AND MC.MOVIE_ID = MI.MOVIE_ID
		AND ML.MOVIE_ID = CC.MOVIE_ID
		AND MK.MOVIE_ID = CC.MOVIE_ID
		AND MC.MOVIE_ID = CC.MOVIE_ID
		AND MI.MOVIE_ID = CC.MOVIE_ID;
