SELECT MIN(T.TITLE) AS MOVIE_TITLE
FROM COMPANY_NAME AS CN, KEYWORD AS K, MOVIE_COMPANIES AS MC, MOVIE_KEYWORD AS MK, TITLE AS T
WHERE CN.COUNTRY_CODE = '[us]'
		AND K.KEYWORD = 'character-name-in-title'
		AND CN.ID = MC.COMPANY_ID
		AND MC.MOVIE_ID = T.ID
		AND T.ID = MK.MOVIE_ID
		AND MK.KEYWORD_ID = K.ID
		AND MC.MOVIE_ID = MK.MOVIE_ID;
