SELECT MIN(MI.INFO) AS MOVIE_BUDGET, MIN(MI_IDX.INFO) AS MOVIE_VOTES, MIN(N.NAME) AS WRITER,
	MIN(T.TITLE) AS VIOLENT_LIONGATE_MOVIE
FROM CAST_INFO AS CI, COMPANY_NAME AS CN, INFO_TYPE AS IT1, INFO_TYPE AS IT2, KEYWORD AS K,
	MOVIE_COMPANIES AS MC, MOVIE_INFO AS MI, MOVIE_INFO_IDX AS MI_IDX, MOVIE_KEYWORD AS MK, NAME AS N, TITLE AS T
WHERE CI.NOTE IN ('(writer)', '(head writer)', '(written by)', '(story)', '(story editor)')
		AND CN.NAME LIKE 'Lionsgate%'
		AND IT1.INFO = 'genres'
		AND IT2.INFO = 'votes'
		AND K.KEYWORD IN ('murder', 'violence', 'blood', 'gore', 'death', 'female-nudity', 'hospital')
		AND MI.INFO IN ('Horror', 'Action', 'Sci-Fi', 'Thriller', 'Crime', 'War')
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MI_IDX.MOVIE_ID
		AND T.ID = CI.MOVIE_ID
		AND T.ID = MK.MOVIE_ID
		AND T.ID = MC.MOVIE_ID
		AND CI.MOVIE_ID = MI.MOVIE_ID
		AND CI.MOVIE_ID = MI_IDX.MOVIE_ID
		AND CI.MOVIE_ID = MK.MOVIE_ID
		AND CI.MOVIE_ID = MC.MOVIE_ID
		AND MI.MOVIE_ID = MI_IDX.MOVIE_ID
		AND MI.MOVIE_ID = MK.MOVIE_ID
		AND MI.MOVIE_ID = MC.MOVIE_ID
		AND MI_IDX.MOVIE_ID = MK.MOVIE_ID
		AND MI_IDX.MOVIE_ID = MC.MOVIE_ID
		AND MK.MOVIE_ID = MC.MOVIE_ID
		AND N.ID = CI.PERSON_ID
		AND IT1.ID = MI.INFO_TYPE_ID
		AND IT2.ID = MI_IDX.INFO_TYPE_ID
		AND K.ID = MK.KEYWORD_ID
		AND CN.ID = MC.COMPANY_ID;
