SELECT MIN(LT.LINK) AS LINK_TYPE, MIN(T1.TITLE) AS FIRST_MOVIE, MIN(T2.TITLE) AS SECOND_MOVIE
FROM KEYWORD AS K, LINK_TYPE AS LT, MOVIE_KEYWORD AS MK, MOVIE_LINK AS ML, TITLE AS T1, TITLE AS T2
WHERE K.KEYWORD = 'character-name-in-title'
		AND MK.KEYWORD_ID = K.ID
		AND T1.ID = MK.MOVIE_ID
		AND ML.MOVIE_ID = T1.ID
		AND ML.LINKED_MOVIE_ID = T2.ID
		AND LT.ID = ML.LINK_TYPE_ID
		AND MK.MOVIE_ID = T1.ID;
