SELECT MIN(CN1.NAME) AS FIRST_COMPANY, MIN(CN2.NAME) AS SECOND_COMPANY, MIN(MI_IDX1.INFO) AS FIRST_RATING,
	MIN(MI_IDX2.INFO) AS SECOND_RATING, MIN(T1.TITLE) AS FIRST_MOVIE, MIN(T2.TITLE) AS SECOND_MOVIE
FROM COMPANY_NAME AS CN1, COMPANY_NAME AS CN2, INFO_TYPE AS IT1, INFO_TYPE AS IT2, KIND_TYPE AS KT1,
	KIND_TYPE AS KT2, LINK_TYPE AS LT, MOVIE_COMPANIES AS MC1, MOVIE_COMPANIES AS MC2,
	MOVIE_INFO_IDX AS MI_IDX1, MOVIE_INFO_IDX AS MI_IDX2, MOVIE_LINK AS ML, TITLE AS T1, TITLE AS T2
WHERE CN1.COUNTRY_CODE = '[nl]'
		AND IT1.INFO = 'rating'
		AND IT2.INFO = 'rating'
		AND KT1.KIND IN ('tv series')
		AND KT2.KIND IN ('tv series')
		AND LT.LINK LIKE '%follow%'
		AND MI_IDX2.INFO < '3.0'
		AND T2.PRODUCTION_YEAR = 2007
		AND LT.ID = ML.LINK_TYPE_ID
		AND T1.ID = ML.MOVIE_ID
		AND T2.ID = ML.LINKED_MOVIE_ID
		AND IT1.ID = MI_IDX1.INFO_TYPE_ID
		AND T1.ID = MI_IDX1.MOVIE_ID
		AND KT1.ID = T1.KIND_ID
		AND CN1.ID = MC1.COMPANY_ID
		AND T1.ID = MC1.MOVIE_ID
		AND ML.MOVIE_ID = MI_IDX1.MOVIE_ID
		AND ML.MOVIE_ID = MC1.MOVIE_ID
		AND MI_IDX1.MOVIE_ID = MC1.MOVIE_ID
		AND IT2.ID = MI_IDX2.INFO_TYPE_ID
		AND T2.ID = MI_IDX2.MOVIE_ID
		AND KT2.ID = T2.KIND_ID
		AND CN2.ID = MC2.COMPANY_ID
		AND T2.ID = MC2.MOVIE_ID
		AND ML.LINKED_MOVIE_ID = MI_IDX2.MOVIE_ID
		AND ML.LINKED_MOVIE_ID = MC2.MOVIE_ID
		AND MI_IDX2.MOVIE_ID = MC2.MOVIE_ID;
