SELECT MIN(MI_IDX.INFO) AS RATING, MIN(T.TITLE) AS MOVIE_TITLE
FROM INFO_TYPE AS IT, KEYWORD AS K, MOVIE_INFO_IDX AS MI_IDX, MOVIE_KEYWORD AS MK, TITLE AS T
WHERE IT.INFO = 'rating'
		AND K.KEYWORD LIKE '%sequel%'
		AND MI_IDX.INFO > '5.0'
		AND T.PRODUCTION_YEAR > 2005
		AND T.ID = MI_IDX.MOVIE_ID
		AND T.ID = MK.MOVIE_ID
		AND MK.MOVIE_ID = MI_IDX.MOVIE_ID
		AND K.ID = MK.KEYWORD_ID
		AND IT.ID = MI_IDX.INFO_TYPE_ID;
