SELECT MIN(T.TITLE) AS TYPICAL_EUROPEAN_MOVIE
FROM COMPANY_TYPE AS CT, INFO_TYPE AS IT, MOVIE_COMPANIES AS MC, MOVIE_INFO AS MI, TITLE AS T
WHERE CT.KIND = 'production companies'
		AND MC.NOTE LIKE '%(theatrical)%'
		AND MC.NOTE LIKE '%(France)%'
		AND MI.INFO IN ('Sweden', 'Norway', 'Germany', 'Denmark', 'Swedish', 'Denish', 'Norwegian', 'German')
		AND T.PRODUCTION_YEAR > 2005
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MC.MOVIE_ID
		AND MC.MOVIE_ID = MI.MOVIE_ID
		AND CT.ID = MC.COMPANY_TYPE_ID
		AND IT.ID = MI.INFO_TYPE_ID;
