SELECT MIN(T.TITLE) AS AMERICAN_VHS_MOVIE
FROM COMPANY_TYPE AS CT, INFO_TYPE AS IT, MOVIE_COMPANIES AS MC, MOVIE_INFO AS MI, TITLE AS T
WHERE CT.KIND = 'production companies'
		AND MC.NOTE LIKE '%(VHS)%'
		AND MC.NOTE LIKE '%(USA)%'
		AND MC.NOTE LIKE '%(1994)%'
		AND MI.INFO IN ('USA', 'America')
		AND T.PRODUCTION_YEAR > 2010
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MC.MOVIE_ID
		AND MC.MOVIE_ID = MI.MOVIE_ID
		AND CT.ID = MC.COMPANY_TYPE_ID
		AND IT.ID = MI.INFO_TYPE_ID;
