SELECT MIN(T.TITLE) AS AMERICAN_MOVIE
FROM COMPANY_TYPE AS CT, INFO_TYPE AS IT, MOVIE_COMPANIES AS MC, MOVIE_INFO AS MI, TITLE AS T
WHERE CT.KIND = 'production companies'
		AND MC.NOTE NOT LIKE '%(TV)%'
		AND MC.NOTE LIKE '%(USA)%'
		AND MI.INFO IN ('Sweden', 'Norway', 'Germany', 'Denmark', 'Swedish', 'Denish', 'Norwegian', 'German',
																			'USA', 'American')
		AND T.PRODUCTION_YEAR > 1990
		AND T.ID = MI.MOVIE_ID
		AND T.ID = MC.MOVIE_ID
		AND MC.MOVIE_ID = MI.MOVIE_ID
		AND CT.ID = MC.COMPANY_TYPE_ID
		AND IT.ID = MI.INFO_TYPE_ID;
