SELECT MIN(N.NAME) AS OF_PERSON, MIN(T.TITLE) AS BIOGRAPHY_MOVIE
FROM AKA_NAME AS AN, CAST_INFO AS CI, INFO_TYPE AS IT, LINK_TYPE AS LT, MOVIE_LINK AS ML, NAME AS N,
	PERSON_INFO AS PI, TITLE AS T
WHERE AN.NAME LIKE '%a%'
		AND IT.INFO = 'mini biography'
		AND LT.LINK = 'features'
		AND N.NAME_PCODE_CF LIKE 'D%'
		AND N.GENDER = 'm'
		AND PI.NOTE = 'Volker Boehm'
		AND T.PRODUCTION_YEAR BETWEEN 1980 AND 1984
		AND N.ID = AN.PERSON_ID
		AND N.ID = PI.PERSON_ID
		AND CI.PERSON_ID = N.ID
		AND T.ID = CI.MOVIE_ID
		AND ML.LINKED_MOVIE_ID = T.ID
		AND LT.ID = ML.LINK_TYPE_ID
		AND IT.ID = PI.INFO_TYPE_ID
		AND PI.PERSON_ID = AN.PERSON_ID
		AND PI.PERSON_ID = CI.PERSON_ID
		AND AN.PERSON_ID = CI.PERSON_ID
		AND CI.MOVIE_ID = ML.LINKED_MOVIE_ID;
