SELECT MIN(N.NAME) AS CAST_MEMBER_NAME, MIN(PI.INFO) AS CAST_MEMBER_INFO
FROM AKA_NAME AS AN, CAST_INFO AS CI, INFO_TYPE AS IT, LINK_TYPE AS LT, MOVIE_LINK AS ML, NAME AS N,
	PERSON_INFO AS PI, TITLE AS T
WHERE AN.NAME IS NOT NULL
		AND (AN.NAME LIKE '%a%'
							OR AN.NAME LIKE 'A%')
		AND IT.INFO = 'mini biography'
		AND LT.LINK IN ('references', 'referenced in', 'features', 'featured in')
		AND N.NAME_PCODE_CF BETWEEN 'A' AND 'F'
		AND (N.GENDER = 'm'
							OR (N.GENDER = 'f'
											AND N.NAME LIKE 'A%'))
		AND PI.NOTE IS NOT NULL
		AND T.PRODUCTION_YEAR BETWEEN 1980 AND 2010
		AND N.ID = AN.PERSON_ID
		AND N.ID = PI.PERSON_ID
		AND CI.PERSON_ID = N.ID
		AND T.ID = CI.MOVIE_ID
		AND ML.LINKED_MOVIE_ID = T.ID
		AND LT.ID = ML.LINK_TYPE_ID
		AND IT.ID = PI.INFO_TYPE_ID
		AND PI.PERSON_ID = AN.PERSON_ID
		AND PI.PERSON_ID = CI.PERSON_ID
		AND AN.PERSON_ID = CI.PERSON_ID
		AND CI.MOVIE_ID = ML.LINKED_MOVIE_ID;
