SELECT MIN(AN1.NAME) AS ACTRESS_PSEUDONYM, MIN(T.TITLE) AS JAPANESE_MOVIE_DUBBED
FROM AKA_NAME AS AN1, CAST_INFO AS CI, COMPANY_NAME AS CN, MOVIE_COMPANIES AS MC, NAME AS N1, ROLE_TYPE AS RT,
	TITLE AS T
WHERE CI.NOTE = '(voice: English version)'
		AND CN.COUNTRY_CODE = '[jp]'
		AND MC.NOTE LIKE '%(Japan)%'
		AND MC.NOTE NOT LIKE '%(USA)%'
		AND N1.NAME LIKE '%Yo%'
		AND N1.NAME NOT LIKE '%Yu%'
		AND RT.ROLE = 'actress'
		AND AN1.PERSON_ID = N1.ID
		AND N1.ID = CI.PERSON_ID
		AND CI.MOVIE_ID = T.ID
		AND T.ID = MC.MOVIE_ID
		AND MC.COMPANY_ID = CN.ID
		AND CI.ROLE_ID = RT.ID
		AND AN1.PERSON_ID = CI.PERSON_ID
		AND CI.MOVIE_ID = MC.MOVIE_ID;
