SELECT MIN(AN.NAME) AS ACRESS_PSEUDONYM, MIN(T.TITLE) AS JAPANESE_ANIME_MOVIE
FROM AKA_NAME AS AN, CAST_INFO AS CI, COMPANY_NAME AS CN, MOVIE_COMPANIES AS MC, NAME AS N, ROLE_TYPE AS RT,
	TITLE AS T
WHERE CI.NOTE = '(voice: English version)'
		AND CN.COUNTRY_CODE = '[jp]'
		AND MC.NOTE LIKE '%(Japan)%'
		AND MC.NOTE NOT LIKE '%(USA)%'
		AND (MC.NOTE LIKE '%(2006)%'
							OR MC.NOTE LIKE '%(2007)%')
		AND N.NAME LIKE '%Yo%'
		AND N.NAME NOT LIKE '%Yu%'
		AND RT.ROLE = 'actress'
		AND T.PRODUCTION_YEAR BETWEEN 2006 AND 2007
		AND (T.TITLE LIKE 'One Piece%'
							OR T.TITLE LIKE 'Dragon Ball Z%')
		AND AN.PERSON_ID = N.ID
		AND N.ID = CI.PERSON_ID
		AND CI.MOVIE_ID = T.ID
		AND T.ID = MC.MOVIE_ID
		AND MC.COMPANY_ID = CN.ID
		AND CI.ROLE_ID = RT.ID
		AND AN.PERSON_ID = CI.PERSON_ID
		AND CI.MOVIE_ID = MC.MOVIE_ID;
