SELECT MIN(A1.NAME) AS WRITER_PSEUDO_NAME, MIN(T.TITLE) AS MOVIE_TITLE
FROM AKA_NAME AS A1, CAST_INFO AS CI, COMPANY_NAME AS CN, MOVIE_COMPANIES AS MC, NAME AS N1, ROLE_TYPE AS RT,
	TITLE AS T
WHERE CN.COUNTRY_CODE = '[us]'
		AND RT.ROLE = 'writer'
		AND A1.PERSON_ID = N1.ID
		AND N1.ID = CI.PERSON_ID
		AND CI.MOVIE_ID = T.ID
		AND T.ID = MC.MOVIE_ID
		AND MC.COMPANY_ID = CN.ID
		AND CI.ROLE_ID = RT.ID
		AND A1.PERSON_ID = CI.PERSON_ID
		AND CI.MOVIE_ID = MC.MOVIE_ID;
