SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%blush%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%snow%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%wheat%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%almond%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%bisque%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%papaya%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%coral%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%orange%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%burnished%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%midnight%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%orchid%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%frosted%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%grey%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%orange%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%black%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%thistle%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%dim%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%chartreuse%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%cornsilk%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%chocolate%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%royal%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%aquamarine%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%bisque%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%chocolate%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%metallic%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%khaki%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%tan%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%sandy%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%thistle%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%tan%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%cornflower%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%cornsilk%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%seashell%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%blanched%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%drab%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%royal%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%goldenrod%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%rosy%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%honeydew%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%violet%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%firebrick%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;

---

SELECT NATION, O_YEAR, SUM(AMOUNT) AS SUM_PROFIT
FROM
		(SELECT N_NAME AS NATION, SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) - PS_SUPPLYCOST * L_QUANTITY AS AMOUNT
			FROM PART, SUPPLIER, LINEITEM, PARTSUPP, ORDERS, NATION
			WHERE S_SUPPKEY = L_SUPPKEY
					AND PS_SUPPKEY = L_SUPPKEY
					AND PS_PARTKEY = L_PARTKEY
					AND P_PARTKEY = L_PARTKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND S_NATIONKEY = N_NATIONKEY
					AND P_NAME like '%blush%') AS PROFIT
GROUP BY NATION, O_YEAR
ORDER BY NATION, O_YEAR DESC;
