SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'EGYPT'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDIA'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ALGERIA'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDIA'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOROCCO'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'JAPAN'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ARGENTINA'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CANADA'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'GERMANY'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'FRANCE'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'GERMANY'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'GERMANY'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'KENYA'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'VIETNAM'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAN'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'UNITED KINGDOM'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'PERU'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ARGENTINA'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'ROMANIA'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'INDIA'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOZAMBIQUE'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAQ'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'PERU'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'MOZAMBIQUE'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'SAUDI ARABIA'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'GERMANY'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'CHINA'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAQ'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;

---

SELECT S_NAME, COUNT(*) AS NUMWAIT
FROM SUPPLIER, LINEITEM L1, ORDERS, NATION
WHERE S_SUPPKEY = L1.L_SUPPKEY
		AND O_ORDERKEY = L1.L_ORDERKEY
		AND O_ORDERSTATUS = 'F'
		AND L1.L_RECEIPTDATE > L1.L_COMMITDATE
		AND EXISTS
				(SELECT *
					FROM LINEITEM L2
					WHERE L2.L_ORDERKEY = L1.L_ORDERKEY
							AND L2.L_SUPPKEY <> L1.L_SUPPKEY)
		AND NOT EXISTS
				(SELECT *
					FROM LINEITEM L3
					WHERE L3.L_ORDERKEY = L1.L_ORDERKEY
							AND L3.L_SUPPKEY <> L1.L_SUPPKEY
							AND L3.L_RECEIPTDATE > L3.L_COMMITDATE )
		AND S_NATIONKEY = N_NATIONKEY
		AND N_NAME = 'IRAN'
GROUP BY S_NAME
ORDER BY NUMWAIT DESC, S_NAME
LIMIT 100;
