SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'JORDAN'
											AND N2.N_NAME = 'UNITED KINGDOM')
										OR (N1.N_NAME = 'UNITED KINGDOM'
														AND N2.N_NAME = 'JORDAN'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'INDONESIA'
											AND N2.N_NAME = 'KENYA')
										OR (N1.N_NAME = 'KENYA'
														AND N2.N_NAME = 'INDONESIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ARGENTINA'
											AND N2.N_NAME = 'CANADA')
										OR (N1.N_NAME = 'CANADA'
														AND N2.N_NAME = 'ARGENTINA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'GERMANY'
											AND N2.N_NAME = 'EGYPT')
										OR (N1.N_NAME = 'EGYPT'
														AND N2.N_NAME = 'GERMANY'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'UNITED KINGDOM'
											AND N2.N_NAME = 'JAPAN')
										OR (N1.N_NAME = 'JAPAN'
														AND N2.N_NAME = 'UNITED KINGDOM'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'GERMANY'
											AND N2.N_NAME = 'VIETNAM')
										OR (N1.N_NAME = 'VIETNAM'
														AND N2.N_NAME = 'GERMANY'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'CHINA'
											AND N2.N_NAME = 'EGYPT')
										OR (N1.N_NAME = 'EGYPT'
														AND N2.N_NAME = 'CHINA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'MOROCCO'
											AND N2.N_NAME = 'ETHIOPIA')
										OR (N1.N_NAME = 'ETHIOPIA'
														AND N2.N_NAME = 'MOROCCO'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ALGERIA'
											AND N2.N_NAME = 'UNITED KINGDOM')
										OR (N1.N_NAME = 'UNITED KINGDOM'
														AND N2.N_NAME = 'ALGERIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'EGYPT'
											AND N2.N_NAME = 'CANADA')
										OR (N1.N_NAME = 'CANADA'
														AND N2.N_NAME = 'EGYPT'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ETHIOPIA'
											AND N2.N_NAME = 'MOZAMBIQUE')
										OR (N1.N_NAME = 'MOZAMBIQUE'
														AND N2.N_NAME = 'ETHIOPIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'RUSSIA'
											AND N2.N_NAME = 'EGYPT')
										OR (N1.N_NAME = 'EGYPT'
														AND N2.N_NAME = 'RUSSIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'INDONESIA'
											AND N2.N_NAME = 'ARGENTINA')
										OR (N1.N_NAME = 'ARGENTINA'
														AND N2.N_NAME = 'INDONESIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'SAUDI ARABIA'
											AND N2.N_NAME = 'ALGERIA')
										OR (N1.N_NAME = 'ALGERIA'
														AND N2.N_NAME = 'SAUDI ARABIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'UNITED STATES'
											AND N2.N_NAME = 'EGYPT')
										OR (N1.N_NAME = 'EGYPT'
														AND N2.N_NAME = 'UNITED STATES'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ALGERIA'
											AND N2.N_NAME = 'PERU')
										OR (N1.N_NAME = 'PERU'
														AND N2.N_NAME = 'ALGERIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'INDIA'
											AND N2.N_NAME = 'CHINA')
										OR (N1.N_NAME = 'CHINA'
														AND N2.N_NAME = 'INDIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'INDONESIA'
											AND N2.N_NAME = 'INDIA')
										OR (N1.N_NAME = 'INDIA'
														AND N2.N_NAME = 'INDONESIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'MOZAMBIQUE'
											AND N2.N_NAME = 'EGYPT')
										OR (N1.N_NAME = 'EGYPT'
														AND N2.N_NAME = 'MOZAMBIQUE'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'BRAZIL'
											AND N2.N_NAME = 'MOZAMBIQUE')
										OR (N1.N_NAME = 'MOZAMBIQUE'
														AND N2.N_NAME = 'BRAZIL'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'EGYPT'
											AND N2.N_NAME = 'UNITED STATES')
										OR (N1.N_NAME = 'UNITED STATES'
														AND N2.N_NAME = 'EGYPT'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'INDIA'
											AND N2.N_NAME = 'INDONESIA')
										OR (N1.N_NAME = 'INDONESIA'
														AND N2.N_NAME = 'INDIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ROMANIA'
											AND N2.N_NAME = 'PERU')
										OR (N1.N_NAME = 'PERU'
														AND N2.N_NAME = 'ROMANIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ROMANIA'
											AND N2.N_NAME = 'GERMANY')
										OR (N1.N_NAME = 'GERMANY'
														AND N2.N_NAME = 'ROMANIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'MOROCCO'
											AND N2.N_NAME = 'JORDAN')
										OR (N1.N_NAME = 'JORDAN'
														AND N2.N_NAME = 'MOROCCO'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'UNITED STATES'
											AND N2.N_NAME = 'VIETNAM')
										OR (N1.N_NAME = 'VIETNAM'
														AND N2.N_NAME = 'UNITED STATES'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'SAUDI ARABIA'
											AND N2.N_NAME = 'VIETNAM')
										OR (N1.N_NAME = 'VIETNAM'
														AND N2.N_NAME = 'SAUDI ARABIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'IRAN'
											AND N2.N_NAME = 'JORDAN')
										OR (N1.N_NAME = 'JORDAN'
														AND N2.N_NAME = 'IRAN'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ALGERIA'
											AND N2.N_NAME = 'ARGENTINA')
										OR (N1.N_NAME = 'ARGENTINA'
														AND N2.N_NAME = 'ALGERIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'KENYA'
											AND N2.N_NAME = 'UNITED STATES')
										OR (N1.N_NAME = 'UNITED STATES'
														AND N2.N_NAME = 'KENYA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ARGENTINA'
											AND N2.N_NAME = 'ALGERIA')
										OR (N1.N_NAME = 'ALGERIA'
														AND N2.N_NAME = 'ARGENTINA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'UNITED STATES'
											AND N2.N_NAME = 'IRAQ')
										OR (N1.N_NAME = 'IRAQ'
														AND N2.N_NAME = 'UNITED STATES'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ALGERIA'
											AND N2.N_NAME = 'IRAN')
										OR (N1.N_NAME = 'IRAN'
														AND N2.N_NAME = 'ALGERIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'BRAZIL'
											AND N2.N_NAME = 'GERMANY')
										OR (N1.N_NAME = 'GERMANY'
														AND N2.N_NAME = 'BRAZIL'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'MOROCCO'
											AND N2.N_NAME = 'RUSSIA')
										OR (N1.N_NAME = 'RUSSIA'
														AND N2.N_NAME = 'MOROCCO'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'JORDAN'
											AND N2.N_NAME = 'ARGENTINA')
										OR (N1.N_NAME = 'ARGENTINA'
														AND N2.N_NAME = 'JORDAN'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'JAPAN'
											AND N2.N_NAME = 'ARGENTINA')
										OR (N1.N_NAME = 'ARGENTINA'
														AND N2.N_NAME = 'JAPAN'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'EGYPT'
											AND N2.N_NAME = 'IRAQ')
										OR (N1.N_NAME = 'IRAQ'
														AND N2.N_NAME = 'EGYPT'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'UNITED KINGDOM'
											AND N2.N_NAME = 'ETHIOPIA')
										OR (N1.N_NAME = 'ETHIOPIA'
														AND N2.N_NAME = 'UNITED KINGDOM'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'JAPAN'
											AND N2.N_NAME = 'BRAZIL')
										OR (N1.N_NAME = 'BRAZIL'
														AND N2.N_NAME = 'JAPAN'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'PERU'
											AND N2.N_NAME = 'VIETNAM')
										OR (N1.N_NAME = 'VIETNAM'
														AND N2.N_NAME = 'PERU'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ARGENTINA'
											AND N2.N_NAME = 'IRAQ')
										OR (N1.N_NAME = 'IRAQ'
														AND N2.N_NAME = 'ARGENTINA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'CANADA'
											AND N2.N_NAME = 'UNITED KINGDOM')
										OR (N1.N_NAME = 'UNITED KINGDOM'
														AND N2.N_NAME = 'CANADA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'GERMANY'
											AND N2.N_NAME = 'BRAZIL')
										OR (N1.N_NAME = 'BRAZIL'
														AND N2.N_NAME = 'GERMANY'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'VIETNAM'
											AND N2.N_NAME = 'GERMANY')
										OR (N1.N_NAME = 'GERMANY'
														AND N2.N_NAME = 'VIETNAM'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'INDIA'
											AND N2.N_NAME = 'PERU')
										OR (N1.N_NAME = 'PERU'
														AND N2.N_NAME = 'INDIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'IRAQ'
											AND N2.N_NAME = 'PERU')
										OR (N1.N_NAME = 'PERU'
														AND N2.N_NAME = 'IRAQ'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'SAUDI ARABIA'
											AND N2.N_NAME = 'IRAN')
										OR (N1.N_NAME = 'IRAN'
														AND N2.N_NAME = 'SAUDI ARABIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'SAUDI ARABIA'
											AND N2.N_NAME = 'JORDAN')
										OR (N1.N_NAME = 'JORDAN'
														AND N2.N_NAME = 'SAUDI ARABIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'MOROCCO'
											AND N2.N_NAME = 'JORDAN')
										OR (N1.N_NAME = 'JORDAN'
														AND N2.N_NAME = 'MOROCCO'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'UNITED KINGDOM'
											AND N2.N_NAME = 'JORDAN')
										OR (N1.N_NAME = 'JORDAN'
														AND N2.N_NAME = 'UNITED KINGDOM'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'SAUDI ARABIA'
											AND N2.N_NAME = 'ROMANIA')
										OR (N1.N_NAME = 'ROMANIA'
														AND N2.N_NAME = 'SAUDI ARABIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'GERMANY'
											AND N2.N_NAME = 'ALGERIA')
										OR (N1.N_NAME = 'ALGERIA'
														AND N2.N_NAME = 'GERMANY'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'MOROCCO'
											AND N2.N_NAME = 'ALGERIA')
										OR (N1.N_NAME = 'ALGERIA'
														AND N2.N_NAME = 'MOROCCO'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'PERU'
											AND N2.N_NAME = 'FRANCE')
										OR (N1.N_NAME = 'FRANCE'
														AND N2.N_NAME = 'PERU'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'VIETNAM'
											AND N2.N_NAME = 'UNITED KINGDOM')
										OR (N1.N_NAME = 'UNITED KINGDOM'
														AND N2.N_NAME = 'VIETNAM'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'JAPAN'
											AND N2.N_NAME = 'IRAN')
										OR (N1.N_NAME = 'IRAN'
														AND N2.N_NAME = 'JAPAN'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ROMANIA'
											AND N2.N_NAME = 'INDONESIA')
										OR (N1.N_NAME = 'INDONESIA'
														AND N2.N_NAME = 'ROMANIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ALGERIA'
											AND N2.N_NAME = 'JORDAN')
										OR (N1.N_NAME = 'JORDAN'
														AND N2.N_NAME = 'ALGERIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'UNITED KINGDOM'
											AND N2.N_NAME = 'CHINA')
										OR (N1.N_NAME = 'CHINA'
														AND N2.N_NAME = 'UNITED KINGDOM'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'CANADA'
											AND N2.N_NAME = 'RUSSIA')
										OR (N1.N_NAME = 'RUSSIA'
														AND N2.N_NAME = 'CANADA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'JAPAN'
											AND N2.N_NAME = 'UNITED STATES')
										OR (N1.N_NAME = 'UNITED STATES'
														AND N2.N_NAME = 'JAPAN'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'INDIA'
											AND N2.N_NAME = 'KENYA')
										OR (N1.N_NAME = 'KENYA'
														AND N2.N_NAME = 'INDIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'JAPAN'
											AND N2.N_NAME = 'FRANCE')
										OR (N1.N_NAME = 'FRANCE'
														AND N2.N_NAME = 'JAPAN'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'FRANCE'
											AND N2.N_NAME = 'KENYA')
										OR (N1.N_NAME = 'KENYA'
														AND N2.N_NAME = 'FRANCE'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'CANADA'
											AND N2.N_NAME = 'ROMANIA')
										OR (N1.N_NAME = 'ROMANIA'
														AND N2.N_NAME = 'CANADA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'RUSSIA'
											AND N2.N_NAME = 'ETHIOPIA')
										OR (N1.N_NAME = 'ETHIOPIA'
														AND N2.N_NAME = 'RUSSIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'FRANCE'
											AND N2.N_NAME = 'IRAQ')
										OR (N1.N_NAME = 'IRAQ'
														AND N2.N_NAME = 'FRANCE'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'JAPAN'
											AND N2.N_NAME = 'JORDAN')
										OR (N1.N_NAME = 'JORDAN'
														AND N2.N_NAME = 'JAPAN'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'UNITED KINGDOM'
											AND N2.N_NAME = 'UNITED STATES')
										OR (N1.N_NAME = 'UNITED STATES'
														AND N2.N_NAME = 'UNITED KINGDOM'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'CANADA'
											AND N2.N_NAME = 'EGYPT')
										OR (N1.N_NAME = 'EGYPT'
														AND N2.N_NAME = 'CANADA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'RUSSIA'
											AND N2.N_NAME = 'ALGERIA')
										OR (N1.N_NAME = 'ALGERIA'
														AND N2.N_NAME = 'RUSSIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'MOROCCO'
											AND N2.N_NAME = 'EGYPT')
										OR (N1.N_NAME = 'EGYPT'
														AND N2.N_NAME = 'MOROCCO'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'CANADA'
											AND N2.N_NAME = 'KENYA')
										OR (N1.N_NAME = 'KENYA'
														AND N2.N_NAME = 'CANADA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'INDIA'
											AND N2.N_NAME = 'PERU')
										OR (N1.N_NAME = 'PERU'
														AND N2.N_NAME = 'INDIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'IRAQ'
											AND N2.N_NAME = 'SAUDI ARABIA')
										OR (N1.N_NAME = 'SAUDI ARABIA'
														AND N2.N_NAME = 'IRAQ'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'UNITED KINGDOM'
											AND N2.N_NAME = 'CHINA')
										OR (N1.N_NAME = 'CHINA'
														AND N2.N_NAME = 'UNITED KINGDOM'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'UNITED KINGDOM'
											AND N2.N_NAME = 'MOZAMBIQUE')
										OR (N1.N_NAME = 'MOZAMBIQUE'
														AND N2.N_NAME = 'UNITED KINGDOM'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'JAPAN'
											AND N2.N_NAME = 'UNITED KINGDOM')
										OR (N1.N_NAME = 'UNITED KINGDOM'
														AND N2.N_NAME = 'JAPAN'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'JORDAN'
											AND N2.N_NAME = 'PERU')
										OR (N1.N_NAME = 'PERU'
														AND N2.N_NAME = 'JORDAN'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'GERMANY'
											AND N2.N_NAME = 'ALGERIA')
										OR (N1.N_NAME = 'ALGERIA'
														AND N2.N_NAME = 'GERMANY'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'SAUDI ARABIA'
											AND N2.N_NAME = 'ALGERIA')
										OR (N1.N_NAME = 'ALGERIA'
														AND N2.N_NAME = 'SAUDI ARABIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ROMANIA'
											AND N2.N_NAME = 'EGYPT')
										OR (N1.N_NAME = 'EGYPT'
														AND N2.N_NAME = 'ROMANIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'FRANCE'
											AND N2.N_NAME = 'ETHIOPIA')
										OR (N1.N_NAME = 'ETHIOPIA'
														AND N2.N_NAME = 'FRANCE'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'RUSSIA'
											AND N2.N_NAME = 'IRAQ')
										OR (N1.N_NAME = 'IRAQ'
														AND N2.N_NAME = 'RUSSIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'EGYPT'
											AND N2.N_NAME = 'UNITED STATES')
										OR (N1.N_NAME = 'UNITED STATES'
														AND N2.N_NAME = 'EGYPT'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'MOZAMBIQUE'
											AND N2.N_NAME = 'BRAZIL')
										OR (N1.N_NAME = 'BRAZIL'
														AND N2.N_NAME = 'MOZAMBIQUE'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'GERMANY'
											AND N2.N_NAME = 'JAPAN')
										OR (N1.N_NAME = 'JAPAN'
														AND N2.N_NAME = 'GERMANY'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'MOZAMBIQUE'
											AND N2.N_NAME = 'EGYPT')
										OR (N1.N_NAME = 'EGYPT'
														AND N2.N_NAME = 'MOZAMBIQUE'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'MOROCCO'
											AND N2.N_NAME = 'CHINA')
										OR (N1.N_NAME = 'CHINA'
														AND N2.N_NAME = 'MOROCCO'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'UNITED STATES'
											AND N2.N_NAME = 'SAUDI ARABIA')
										OR (N1.N_NAME = 'SAUDI ARABIA'
														AND N2.N_NAME = 'UNITED STATES'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'PERU'
											AND N2.N_NAME = 'ETHIOPIA')
										OR (N1.N_NAME = 'ETHIOPIA'
														AND N2.N_NAME = 'PERU'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'RUSSIA'
											AND N2.N_NAME = 'JAPAN')
										OR (N1.N_NAME = 'JAPAN'
														AND N2.N_NAME = 'RUSSIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ROMANIA'
											AND N2.N_NAME = 'CHINA')
										OR (N1.N_NAME = 'CHINA'
														AND N2.N_NAME = 'ROMANIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'ALGERIA'
											AND N2.N_NAME = 'INDIA')
										OR (N1.N_NAME = 'INDIA'
														AND N2.N_NAME = 'ALGERIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'IRAN'
											AND N2.N_NAME = 'KENYA')
										OR (N1.N_NAME = 'KENYA'
														AND N2.N_NAME = 'IRAN'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'MOZAMBIQUE'
											AND N2.N_NAME = 'SAUDI ARABIA')
										OR (N1.N_NAME = 'SAUDI ARABIA'
														AND N2.N_NAME = 'MOZAMBIQUE'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'RUSSIA'
											AND N2.N_NAME = 'ARGENTINA')
										OR (N1.N_NAME = 'ARGENTINA'
														AND N2.N_NAME = 'RUSSIA'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'IRAN'
											AND N2.N_NAME = 'MOZAMBIQUE')
										OR (N1.N_NAME = 'MOZAMBIQUE'
														AND N2.N_NAME = 'IRAN'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;

---

SELECT SUPP_NATION, CUST_NATION, L_YEAR, SUM(VOLUME) AS REVENUE
FROM
		(SELECT N1.N_NAME AS SUPP_NATION, N2.N_NAME AS CUST_NATION, SUBSTR(L_SHIPDATE,
																																																																1, 4) AS L_YEAR,
				L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
			FROM SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2
			WHERE S_SUPPKEY = L_SUPPKEY
					AND O_ORDERKEY = L_ORDERKEY
					AND C_CUSTKEY = O_CUSTKEY
					AND S_NATIONKEY = N1.N_NATIONKEY
					AND C_NATIONKEY = N2.N_NATIONKEY
					AND ((N1.N_NAME = 'IRAQ'
											AND N2.N_NAME = 'ARGENTINA')
										OR (N1.N_NAME = 'ARGENTINA'
														AND N2.N_NAME = 'IRAQ'))
					AND L_SHIPDATE BETWEEN '1995-01-01' AND '1996-12-31' ) AS SHIPPING
GROUP BY SUPP_NATION, CUST_NATION, L_YEAR
ORDER BY SUPP_NATION, CUST_NATION, L_YEAR;
