SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1996-01-01'
		AND O_ORDERDATE < '1997-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1995-01-01'
		AND O_ORDERDATE < '1996-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND O_ORDERDATE >= '1997-01-01'
		AND O_ORDERDATE < '1998-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND O_ORDERDATE >= '1994-01-01'
		AND O_ORDERDATE < '1995-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;

---

SELECT N_NAME, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE
FROM CUSTOMER, ORDERS, LINEITEM, SUPPLIER, NATION, REGION
WHERE C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND L_SUPPKEY = S_SUPPKEY
		AND C_NATIONKEY = S_NATIONKEY
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND O_ORDERDATE >= '1993-01-01'
		AND O_ORDERDATE < '1994-01-01'
GROUP BY N_NAME
ORDER BY REVENUE DESC;
