SELECT O_YEAR,
	SUM(CASE
									WHEN NATION = 'SAUDI ARABIA' THEN VOLUME
									ELSE 0
					END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL BURNISHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ALGERIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM PLATED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ARGENTINA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL PLATED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'EGYPT' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD PLATED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ROMANIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO BURNISHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ALGERIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO BRUSHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'PERU' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE BRUSHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'IRAQ' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO BURNISHED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR,
	SUM(CASE
									WHEN NATION = 'UNITED STATES' THEN VOLUME
									ELSE 0
					END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE BRUSHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'BRAZIL' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM PLATED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'MOROCCO' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD BRUSHED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ETHIOPIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM BRUSHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'INDIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM PLATED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'KENYA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO ANODIZED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'JORDAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM POLISHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'JAPAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL BRUSHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'BRAZIL' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO POLISHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'BRAZIL' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM ANODIZED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'INDIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY POLISHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR,
	SUM(CASE
									WHEN NATION = 'SAUDI ARABIA' THEN VOLUME
									ELSE 0
					END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY POLISHED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'RUSSIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL PLATED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'PERU' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM PLATED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'EGYPT' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY ANODIZED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'VIETNAM' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE PLATED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ETHIOPIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO BURNISHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'RUSSIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD ANODIZED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ROMANIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE ANODIZED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR,
	SUM(CASE
									WHEN NATION = 'UNITED KINGDOM' THEN VOLUME
									ELSE 0
					END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL BRUSHED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'JAPAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL ANODIZED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'IRAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD ANODIZED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'FRANCE' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY BRUSHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'INDIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE ANODIZED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'IRAQ' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE PLATED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'EGYPT' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO ANODIZED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'BRAZIL' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE BURNISHED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'INDONESIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD POLISHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'GERMANY' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY POLISHED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'RUSSIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY POLISHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ALGERIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO POLISHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'EGYPT' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO BRUSHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'INDIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD POLISHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'BRAZIL' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM ANODIZED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'EGYPT' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE BRUSHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR,
	SUM(CASE
									WHEN NATION = 'UNITED KINGDOM' THEN VOLUME
									ELSE 0
					END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE BURNISHED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'INDONESIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY BURNISHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'GERMANY' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM BURNISHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'JORDAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY ANODIZED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'JORDAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM BURNISHED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'EGYPT' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM PLATED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'MOZAMBIQUE' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL POLISHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ARGENTINA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY BRUSHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'JAPAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD ANODIZED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR,
	SUM(CASE
									WHEN NATION = 'UNITED STATES' THEN VOLUME
									ELSE 0
					END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM PLATED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR,
	SUM(CASE
									WHEN NATION = 'SAUDI ARABIA' THEN VOLUME
									ELSE 0
					END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM POLISHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'IRAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY PLATED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ETHIOPIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD ANODIZED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'JORDAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY PLATED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'MOROCCO' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY POLISHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'CHINA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL POLISHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'KENYA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO BURNISHED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'GERMANY' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD PLATED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'EGYPT' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD BURNISHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'MOROCCO' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY ANODIZED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ETHIOPIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO ANODIZED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ETHIOPIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE POLISHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'FRANCE' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL POLISHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ROMANIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM PLATED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'FRANCE' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM BRUSHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'MOROCCO' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD PLATED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'IRAQ' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE PLATED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'VIETNAM' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY BRUSHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR,
	SUM(CASE
									WHEN NATION = 'UNITED STATES' THEN VOLUME
									ELSE 0
					END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD POLISHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'PERU' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM BRUSHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ALGERIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE PLATED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'CHINA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL ANODIZED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'RUSSIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY BRUSHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ARGENTINA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO ANODIZED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'RUSSIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD BRUSHED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'MOROCCO' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD BURNISHED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'CHINA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'ECONOMY BRUSHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ROMANIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO BRUSHED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'JAPAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM ANODIZED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR,
	SUM(CASE
									WHEN NATION = 'SAUDI ARABIA' THEN VOLUME
									ELSE 0
					END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM PLATED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'CHINA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'ASIA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE POLISHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ROMANIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM BURNISHED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'RUSSIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO PLATED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'RUSSIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE ANODIZED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR,
	SUM(CASE
									WHEN NATION = 'SAUDI ARABIA' THEN VOLUME
									ELSE 0
					END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE ANODIZED NICKEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR,
	SUM(CASE
									WHEN NATION = 'UNITED STATES' THEN VOLUME
									ELSE 0
					END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO ANODIZED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'EGYPT' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE BRUSHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'IRAQ' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD BRUSHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ROMANIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL ANODIZED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR,
	SUM(CASE
									WHEN NATION = 'UNITED KINGDOM' THEN VOLUME
									ELSE 0
					END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'LARGE PLATED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'MOROCCO' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AFRICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO BRUSHED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'IRAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL BRUSHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'JORDAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO PLATED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'JORDAN' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'MEDIUM BRUSHED TIN') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'ROMANIA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'EUROPE'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'SMALL PLATED STEEL') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'CANADA' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'AMERICA'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'STANDARD POLISHED BRASS') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;

---

SELECT O_YEAR, SUM(CASE
																							WHEN NATION = 'IRAQ' THEN VOLUME
																							ELSE 0
																			END) / SUM(VOLUME) AS MKT_SHARE
FROM
		(SELECT SUBSTR(O_ORDERDATE, 1, 4) AS O_YEAR, L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME, N2.N_NAME AS NATION
			FROM PART, SUPPLIER, LINEITEM, ORDERS, CUSTOMER, NATION N1, NATION N2, REGION
			WHERE P_PARTKEY = L_PARTKEY
					AND S_SUPPKEY = L_SUPPKEY
					AND L_ORDERKEY = O_ORDERKEY
					AND O_CUSTKEY = C_CUSTKEY
					AND C_NATIONKEY = N1.N_NATIONKEY
					AND N1.N_REGIONKEY = R_REGIONKEY
					AND R_NAME = 'MIDDLE EAST'
					AND S_NATIONKEY = N2.N_NATIONKEY
					AND O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31'
					AND P_TYPE = 'PROMO BRUSHED COPPER') AS ALL_NATIONS
GROUP BY O_YEAR
ORDER BY O_YEAR;
