SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-19'
		AND L_SHIPDATE > '1995-03-19'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-10'
		AND L_SHIPDATE > '1995-03-10'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-06'
		AND L_SHIPDATE > '1995-03-06'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-17'
		AND L_SHIPDATE > '1995-03-17'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-29'
		AND L_SHIPDATE > '1995-03-29'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-24'
		AND L_SHIPDATE > '1995-03-24'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-26'
		AND L_SHIPDATE > '1995-03-26'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-23'
		AND L_SHIPDATE > '1995-03-23'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-02'
		AND L_SHIPDATE > '1995-03-02'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-23'
		AND L_SHIPDATE > '1995-03-23'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-18'
		AND L_SHIPDATE > '1995-03-18'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-06'
		AND L_SHIPDATE > '1995-03-06'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-06'
		AND L_SHIPDATE > '1995-03-06'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-14'
		AND L_SHIPDATE > '1995-03-14'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-07'
		AND L_SHIPDATE > '1995-03-07'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-30'
		AND L_SHIPDATE > '1995-03-30'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-19'
		AND L_SHIPDATE > '1995-03-19'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-19'
		AND L_SHIPDATE > '1995-03-19'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-03'
		AND L_SHIPDATE > '1995-03-03'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-15'
		AND L_SHIPDATE > '1995-03-15'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-30'
		AND L_SHIPDATE > '1995-03-30'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-13'
		AND L_SHIPDATE > '1995-03-13'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-12'
		AND L_SHIPDATE > '1995-03-12'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-04'
		AND L_SHIPDATE > '1995-03-04'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-18'
		AND L_SHIPDATE > '1995-03-18'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-21'
		AND L_SHIPDATE > '1995-03-21'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-13'
		AND L_SHIPDATE > '1995-03-13'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-23'
		AND L_SHIPDATE > '1995-03-23'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-01'
		AND L_SHIPDATE > '1995-03-01'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-04'
		AND L_SHIPDATE > '1995-03-04'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-12'
		AND L_SHIPDATE > '1995-03-12'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-07'
		AND L_SHIPDATE > '1995-03-07'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-12'
		AND L_SHIPDATE > '1995-03-12'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-10'
		AND L_SHIPDATE > '1995-03-10'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-30'
		AND L_SHIPDATE > '1995-03-30'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-06'
		AND L_SHIPDATE > '1995-03-06'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-02'
		AND L_SHIPDATE > '1995-03-02'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-11'
		AND L_SHIPDATE > '1995-03-11'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-03'
		AND L_SHIPDATE > '1995-03-03'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-05'
		AND L_SHIPDATE > '1995-03-05'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-13'
		AND L_SHIPDATE > '1995-03-13'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-29'
		AND L_SHIPDATE > '1995-03-29'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-23'
		AND L_SHIPDATE > '1995-03-23'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-14'
		AND L_SHIPDATE > '1995-03-14'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-06'
		AND L_SHIPDATE > '1995-03-06'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-20'
		AND L_SHIPDATE > '1995-03-20'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-14'
		AND L_SHIPDATE > '1995-03-14'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-25'
		AND L_SHIPDATE > '1995-03-25'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-19'
		AND L_SHIPDATE > '1995-03-19'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-27'
		AND L_SHIPDATE > '1995-03-27'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-12'
		AND L_SHIPDATE > '1995-03-12'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-10'
		AND L_SHIPDATE > '1995-03-10'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-30'
		AND L_SHIPDATE > '1995-03-30'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-13'
		AND L_SHIPDATE > '1995-03-13'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-02'
		AND L_SHIPDATE > '1995-03-02'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-26'
		AND L_SHIPDATE > '1995-03-26'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-09'
		AND L_SHIPDATE > '1995-03-09'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-27'
		AND L_SHIPDATE > '1995-03-27'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-17'
		AND L_SHIPDATE > '1995-03-17'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-05'
		AND L_SHIPDATE > '1995-03-05'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-05'
		AND L_SHIPDATE > '1995-03-05'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-09'
		AND L_SHIPDATE > '1995-03-09'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-02'
		AND L_SHIPDATE > '1995-03-02'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-27'
		AND L_SHIPDATE > '1995-03-27'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-15'
		AND L_SHIPDATE > '1995-03-15'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-22'
		AND L_SHIPDATE > '1995-03-22'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-04'
		AND L_SHIPDATE > '1995-03-04'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-08'
		AND L_SHIPDATE > '1995-03-08'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-22'
		AND L_SHIPDATE > '1995-03-22'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-13'
		AND L_SHIPDATE > '1995-03-13'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-22'
		AND L_SHIPDATE > '1995-03-22'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-31'
		AND L_SHIPDATE > '1995-03-31'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-09'
		AND L_SHIPDATE > '1995-03-09'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-04'
		AND L_SHIPDATE > '1995-03-04'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-06'
		AND L_SHIPDATE > '1995-03-06'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-06'
		AND L_SHIPDATE > '1995-03-06'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-08'
		AND L_SHIPDATE > '1995-03-08'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-04'
		AND L_SHIPDATE > '1995-03-04'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-23'
		AND L_SHIPDATE > '1995-03-23'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-05'
		AND L_SHIPDATE > '1995-03-05'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-15'
		AND L_SHIPDATE > '1995-03-15'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-26'
		AND L_SHIPDATE > '1995-03-26'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-19'
		AND L_SHIPDATE > '1995-03-19'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-24'
		AND L_SHIPDATE > '1995-03-24'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-08'
		AND L_SHIPDATE > '1995-03-08'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-08'
		AND L_SHIPDATE > '1995-03-08'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-11'
		AND L_SHIPDATE > '1995-03-11'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-29'
		AND L_SHIPDATE > '1995-03-29'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-01'
		AND L_SHIPDATE > '1995-03-01'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-27'
		AND L_SHIPDATE > '1995-03-27'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-15'
		AND L_SHIPDATE > '1995-03-15'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-29'
		AND L_SHIPDATE > '1995-03-29'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-30'
		AND L_SHIPDATE > '1995-03-30'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'HOUSEHOLD'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-27'
		AND L_SHIPDATE > '1995-03-27'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'BUILDING'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-28'
		AND L_SHIPDATE > '1995-03-28'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-10'
		AND L_SHIPDATE > '1995-03-10'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'MACHINERY'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-25'
		AND L_SHIPDATE > '1995-03-25'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'FURNITURE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-19'
		AND L_SHIPDATE > '1995-03-19'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-22'
		AND L_SHIPDATE > '1995-03-22'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;

---

SELECT L_ORDERKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) AS REVENUE, O_ORDERDATE, O_SHIPPRIORITY
FROM CUSTOMER, ORDERS, LINEITEM
WHERE C_MKTSEGMENT = 'AUTOMOBILE'
		AND C_CUSTKEY = O_CUSTKEY
		AND L_ORDERKEY = O_ORDERKEY
		AND O_ORDERDATE < '1995-03-15'
		AND L_SHIPDATE > '1995-03-15'
GROUP BY L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY
ORDER BY REVENUE DESC, O_ORDERDATE
LIMIT 10;
