SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 49
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 45
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 49
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 46
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 21
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 20
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 28
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 31
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 43
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 4
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 40
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 31
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 16
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 46
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 9
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 23
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 9
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 26
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 34
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 42
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 9
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 6
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 34
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 8
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 30
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 10
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 5
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 7
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 48
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 28
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 24
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 11
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 31
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 13
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 9
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 20
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 38
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 42
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 8
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 48
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 40
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 8
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 15
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 43
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 16
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 4
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 23
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 46
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 41
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 31
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 12
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 48
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 27
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 23
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 49
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 19
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 3
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 50
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 41
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 16
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 21
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 50
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 46
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 26
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 46
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 16
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 17
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 13
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 10
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 39
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 10
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 17
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 41
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 13
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 13
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 15
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 43
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 6
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 1
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 25
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 7
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 32
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 35
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 9
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 20
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 40
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 24
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 30
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 49
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 21
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'EUROPE'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'EUROPE')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 48
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 47
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 17
		AND P_TYPE like '%NICKEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 24
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 23
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 21
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AMERICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AMERICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 38
		AND P_TYPE like '%TIN'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'AFRICA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'AFRICA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 19
		AND P_TYPE like '%STEEL'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'MIDDLE EAST'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'MIDDLE EAST')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 1
		AND P_TYPE like '%BRASS'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;

---

SELECT S_ACCTBAL, S_NAME, N_NAME, P_PARTKEY, P_MFGR, S_ADDRESS, S_PHONE, S_COMMENT
FROM PART, SUPPLIER, PARTSUPP, NATION, REGION
WHERE P_PARTKEY = PS_PARTKEY
		AND S_SUPPKEY = PS_SUPPKEY
		AND P_SIZE = 15
		AND P_TYPE like '%COPPER'
		AND S_NATIONKEY = N_NATIONKEY
		AND N_REGIONKEY = R_REGIONKEY
		AND R_NAME = 'ASIA'
		AND PS_SUPPLYCOST =
				(SELECT MIN(PS_SUPPLYCOST)
					FROM PARTSUPP, SUPPLIER, NATION, REGION
					WHERE P_PARTKEY = PS_PARTKEY
							AND S_SUPPKEY = PS_SUPPKEY
							AND S_NATIONKEY = N_NATIONKEY
							AND N_REGIONKEY = R_REGIONKEY
							AND R_NAME = 'ASIA')
ORDER BY S_ACCTBAL DESC, N_NAME, S_NAME, P_PARTKEY
LIMIT 100;
