name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose up --build --quiet-pull -d backend generator manager frontend influxdb
    - name: Check running containers
      run: docker ps -a
    - name: Check logs Backend
      run: docker logs cockpit_backend_1
    - name: Check logs Generator
      run: docker logs cockpit_generator_1
    - name: Check logs Manager
      run: docker logs cockpit_manager_1
    - name: Check logs Frontend
      run: docker logs cockpit_frontend_1