name: Docker Image CI

on: [push]

jobs:

  backend_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build backend container
      run: docker-compose up --build --quiet-pull -d backend
    - name: Check running containers
      run: docker ps -a
    - name: Check logs Backend
      run: docker logs backend_1

  frontend_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the frontend container
      run: docker-compose up --build --quiet-pull -d frontend
    - name: Check running containers
      run: docker ps -a
    - name: Check logs Frontend
      run: docker logs cockpit_frontend_1
  
