name: Docker Image CI

on: [push]

jobs:

  backend_build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Copy environment file
      run: cp .env.example .env
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.ci.yml up --build --quiet-pull -d backend generator manager influxdb hyrise curler
    - name: Check running containers
      run: docker ps -a
    - name: Check logs Backend
      run: docker logs cockpit_backend_1
    - name: Check logs Generator
      run: docker logs cockpit_generator_1
    - name: Check logs Manager
      run: docker logs cockpit_manager_1
    - name: Check Swagger Availability
      run: 'docker exec cockpit_curler_1 curl -X POST http://backend:8000/control/database/ -H accept: application/json -H Content-Type: application/json -d {  "password": "password",  "dbname": "postgres",  "port": "5432",  "host": "hyrise",  "user": "user",  "number_workers": 8,  "id": "hyrise" }'
    - name: Check running containers
      run: docker ps -a
    - name: Check logs Backend
      run: docker logs cockpit_backend_1
    - name: Check logs Generator
      run: docker logs cockpit_generator_1
    - name: Check logs Manager
      run: docker logs cockpit_manager_1

  frontend_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the frontend container
      run: docker-compose up --build --quiet-pull -d frontend
    - name: Check logs Frontend
      run: docker logs cockpit_frontend_1