name: Docker Deployment CI

on:
  push:
    branches:
      - master
      - dev
jobs:

  backend_push:

    runs-on: ubuntu-latest

    step: 
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      password: ${{ secrets.DOCKER_HUB_TOKEN }}
      repository: hyrise/bp1920
      tags: cockpit-backend
      dockerfile: ./hyrisecockpit/Dockerfile

  frontend_push:

    runs-on: ubuntu-latest

    step: 
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      password: ${{ secrets.DOCKER_HUB_TOKEN }}
      repository: hyrise/bp1920
      tags: cockpit-frontent
      dockerfile: ./hyrisecockpit/frontend/Dockerfile
