name: Frontend Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
      working-directory: ./hyrisecockpit/frontend
    - run: npm run lint > lint-output.txt
      working-directory: ./hyrisecockpit/frontend
    - run:   echo ::set-output name=success::$(grep "No lint errors found!" lint-output.txt | wc -l)
      id:    counter
      shell: bash 
      working-directory: ./hyrisecockpit/frontend
    - run: exit 1
      if:  steps.counter.outputs.success == '0'
      working-directory: ./hyrisecockpit/frontend


