name: Frontend Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
      working-directory: ./hyrisecockpit/frontend
    - run: npm test
      working-directory: ./hyrisecockpit/frontend

