name: Frontend Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
      working-directory: ./hyrisecockpit/frontend
    - run: npm run lint > lint-output.txt
      working-directory: ./hyrisecockpit/frontend
    - if: (grep -q "No lint errors found!" "lint-output.txt"; echo $?) == 1
    - run: exit 1
      working-directory: ./hyrisecockpit/frontend


