name: Frontend Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - uses: eslint/github-action@v0
      with: 
        entrypoint: ./hyrisecockpit/frontend

