name: Python application

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.9
    - name: Install libpq PostgreSQL client
      run: sudo apt-get -yqq install libpq-dev
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install pipenv virtual environment with dev dependencies
      run: |
        pipenv --bare install --dev
    - name: Run all pre-commit hooks
      run: |
        pipenv run pre-commit run --all-files
    - name: Run all python tests
      run: |
        pipenv run pytest
