name: Python application

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.9
    - name: Set up pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dev dependencies
      run: |
        pipenv install --dev
    - name: Run all pre-commit hooks
      run: |
        pipenv run pre-commit run --all-files
