WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;

---

WITH CUSTOMER_TOTAL_RETURN AS
		(SELECT SR_CUSTOMER_SK AS CTR_CUSTOMER_SK, SR_STORE_SK AS CTR_STORE_SK, SUM(SR_RETURN_AMT) AS CTR_TOTAL_RETURN
			FROM STORE_RETURNS, DATE_DIM
			WHERE SR_RETURNED_DATE_SK = D_DATE_SK
					AND D_YEAR = 2000
			GROUP BY SR_CUSTOMER_SK, SR_STORE_SK)
SELECT C_CUSTOMER_ID
FROM CUSTOMER_TOTAL_RETURN CTR1, STORE, CUSTOMER
WHERE CTR1.CTR_TOTAL_RETURN >
				(SELECT AVG(CTR_TOTAL_RETURN) * 1.2
					FROM CUSTOMER_TOTAL_RETURN CTR2
					WHERE CTR1.CTR_STORE_SK = CTR2.CTR_STORE_SK)
		AND S_STORE_SK = CTR1.CTR_STORE_SK
		AND S_STATE = 'TN'
		AND CTR1.CTR_CUSTOMER_SK = C_CUSTOMER_SK
ORDER BY C_CUSTOMER_ID
LIMIT 100;
