SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) SUM_AGG
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANUFACT_ID = 128
		AND DT.D_MOY = 11
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, SUM_AGG DESC, BRAND_ID
LIMIT 100;
