SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;

---

SELECT A.CA_STATE STATE, COUNT(*) CNT
FROM CUSTOMER_ADDRESS A, CUSTOMER C, STORE_SALES S, DATE_DIM D, ITEM I
WHERE A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
		AND C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
		AND S.SS_SOLD_DATE_SK = D.D_DATE_SK
		AND S.SS_ITEM_SK = I.I_ITEM_SK
		AND D.D_MONTH_SEQ =
				(SELECT DISTINCT (D_MONTH_SEQ)
					FROM DATE_DIM
					WHERE D_YEAR = 2001
							AND D_MOY = 1 )
		AND I.I_CURRENT_PRICE > 1.2 *
				(SELECT AVG(J.I_CURRENT_PRICE)
					FROM ITEM J
					WHERE J.I_CATEGORY = I.I_CATEGORY)
GROUP BY A.CA_STATE
HAVING COUNT(*) >= 10
ORDER BY CNT, A.CA_STATE
LIMIT 100;
