SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, I_MANUFACT_ID, I_MANUFACT, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM, CUSTOMER, CUSTOMER_ADDRESS, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 8
		AND D_MOY = 11
		AND D_YEAR = 1998
		AND SS_CUSTOMER_SK = C_CUSTOMER_SK
		AND C_CURRENT_ADDR_SK = CA_ADDRESS_SK
		AND SUBSTR(CA_ZIP, 1, 5) <> SUBSTR(S_ZIP, 1, 5)
		AND SS_STORE_SK = S_STORE_SK
GROUP BY I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
ORDER BY EXT_PRICE DESC, I_BRAND, I_BRAND_ID, I_MANUFACT_ID, I_MANUFACT
LIMIT 100 ;
