SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_NET_PROFIT) AS STORE_SALES_PROFIT,
	SUM(SR_NET_LOSS) AS STORE_RETURNS_LOSS, SUM(CS_NET_PROFIT) AS CATALOG_SALES_PROFIT
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 4
		AND D1.D_YEAR = 2001
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 4 AND 10
		AND D2.D_YEAR = 2001
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_MOY BETWEEN 4 AND 10
		AND D3.D_YEAR = 2001
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;
