SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;

---

SELECT I_ITEM_ID, AVG(CS_QUANTITY) AGG1, AVG(CS_LIST_PRICE) AGG2, AVG(CS_COUPON_AMT) AGG3,
	AVG(CS_SALES_PRICE) AGG4
FROM CATALOG_SALES, CUSTOMER_DEMOGRAPHICS, DATE_DIM, ITEM, PROMOTION
WHERE CS_SOLD_DATE_SK = D_DATE_SK
		AND CS_ITEM_SK = I_ITEM_SK
		AND CS_BILL_CDEMO_SK = CD_DEMO_SK
		AND CS_PROMO_SK = P_PROMO_SK
		AND CD_GENDER = 'M'
		AND CD_MARITAL_STATUS = 'S'
		AND CD_EDUCATION_STATUS = 'College'
		AND (P_CHANNEL_EMAIL = 'N'
							OR P_CHANNEL_EVENT = 'N')
		AND D_YEAR = 2000
GROUP BY I_ITEM_ID
ORDER BY I_ITEM_ID
LIMIT 100;
