SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;

---

SELECT I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME, SUM(SS_QUANTITY) AS STORE_SALES_QUANTITY,
	SUM(SR_RETURN_QUANTITY) AS STORE_RETURNS_QUANTITY, SUM(CS_QUANTITY) AS CATALOG_SALES_QUANTITY
FROM STORE_SALES, STORE_RETURNS, CATALOG_SALES, DATE_DIM D1, DATE_DIM D2, DATE_DIM D3, STORE, ITEM
WHERE D1.D_MOY = 9
		AND D1.D_YEAR = 1999
		AND D1.D_DATE_SK = SS_SOLD_DATE_SK
		AND I_ITEM_SK = SS_ITEM_SK
		AND S_STORE_SK = SS_STORE_SK
		AND SS_CUSTOMER_SK = SR_CUSTOMER_SK
		AND SS_ITEM_SK = SR_ITEM_SK
		AND SS_TICKET_NUMBER = SR_TICKET_NUMBER
		AND SR_RETURNED_DATE_SK = D2.D_DATE_SK
		AND D2.D_MOY BETWEEN 9 AND 9 + 3
		AND D2.D_YEAR = 1999
		AND SR_CUSTOMER_SK = CS_BILL_CUSTOMER_SK
		AND SR_ITEM_SK = CS_ITEM_SK
		AND CS_SOLD_DATE_SK = D3.D_DATE_SK
		AND D3.D_YEAR IN (1999, 1999 + 1, 1999 + 2)
GROUP BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
ORDER BY I_ITEM_ID, I_ITEM_DESC, S_STORE_ID, S_STORE_NAME
LIMIT 100;
