WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;

---

WITH INV AS
		(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDEV, MEAN,
				CASE MEAN
								WHEN 0 THEN NULL
								ELSE STDEV / MEAN
				END COV
			FROM
					(SELECT W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, STDDEV_SAMP(INV_QUANTITY_ON_HAND) STDEV,
							AVG(INV_QUANTITY_ON_HAND) MEAN
						FROM INVENTORY, ITEM, WAREHOUSE, DATE_DIM
						WHERE INV_ITEM_SK = I_ITEM_SK
								AND INV_WAREHOUSE_SK = W_WAREHOUSE_SK
								AND INV_DATE_SK = D_DATE_SK
								AND D_YEAR = 2001
						GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY) FOO
			WHERE CASE MEAN
													WHEN 0 THEN 0
													ELSE STDEV / MEAN
									END > 1)
SELECT INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.W_WAREHOUSE_SK, INV2.I_ITEM_SK,
	INV2.D_MOY, INV2.MEAN, INV2.COV
FROM INV INV1, INV INV2
WHERE INV1.I_ITEM_SK = INV2.I_ITEM_SK
		AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
		AND INV1.D_MOY = 1
		AND INV2.D_MOY = 1 + 1
ORDER BY INV1.W_WAREHOUSE_SK, INV1.I_ITEM_SK, INV1.D_MOY, INV1.MEAN, INV1.COV, INV2.D_MOY, INV2.MEAN, INV2.COV ;
