SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;

---

SELECT S_STORE_NAME, S_STORE_ID,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Sunday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SUN_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Monday') THEN SS_SALES_PRICE
									ELSE NULL
					END) MON_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Tuesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) TUE_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Wednesday') THEN SS_SALES_PRICE
									ELSE NULL
					END) WED_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Thursday') THEN SS_SALES_PRICE
									ELSE NULL
					END) THU_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Friday') THEN SS_SALES_PRICE
									ELSE NULL
					END) FRI_SALES,
	SUM(CASE
									WHEN (D_DAY_NAME = 'Saturday') THEN SS_SALES_PRICE
									ELSE NULL
					END) SAT_SALES
FROM DATE_DIM, STORE_SALES, STORE
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND S_STORE_SK = SS_STORE_SK
		AND S_GMT_OFFSET = -5
		AND D_YEAR = 2000
GROUP BY S_STORE_NAME, S_STORE_ID
ORDER BY S_STORE_NAME, S_STORE_ID, SUN_SALES, MON_SALES, TUE_SALES, WED_SALES, THU_SALES, FRI_SALES, SAT_SALES
LIMIT 100;
