SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;

---

SELECT DT.D_YEAR, ITEM.I_BRAND_ID BRAND_ID, ITEM.I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM DT, STORE_SALES, ITEM
WHERE DT.D_DATE_SK = STORE_SALES.SS_SOLD_DATE_SK
		AND STORE_SALES.SS_ITEM_SK = ITEM.I_ITEM_SK
		AND ITEM.I_MANAGER_ID = 1
		AND DT.D_MOY = 11
		AND DT.D_YEAR = 2000
GROUP BY DT.D_YEAR, ITEM.I_BRAND, ITEM.I_BRAND_ID
ORDER BY DT.D_YEAR, EXT_PRICE DESC, BRAND_ID
LIMIT 100 ;
