SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;

---

SELECT I_BRAND_ID BRAND_ID, I_BRAND BRAND, SUM(SS_EXT_SALES_PRICE) EXT_PRICE
FROM DATE_DIM, STORE_SALES, ITEM
WHERE D_DATE_SK = SS_SOLD_DATE_SK
		AND SS_ITEM_SK = I_ITEM_SK
		AND I_MANAGER_ID = 28
		AND D_MOY = 11
		AND D_YEAR = 1999
GROUP BY I_BRAND, I_BRAND_ID
ORDER BY EXT_PRICE DESC, I_BRAND_ID
LIMIT 100 ;
