SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;

---

SELECT S_STORE_NAME, I_ITEM_DESC, SC.REVENUE, I_CURRENT_PRICE, I_WHOLESALE_COST, I_BRAND
FROM STORE, ITEM,

		(SELECT SS_STORE_SK, AVG(REVENUE) AS AVE
			FROM
					(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
						FROM STORE_SALES, DATE_DIM
						WHERE SS_SOLD_DATE_SK = D_DATE_SK
								AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
						GROUP BY SS_STORE_SK, SS_ITEM_SK) SA
			GROUP BY SS_STORE_SK) SB,

		(SELECT SS_STORE_SK, SS_ITEM_SK, SUM(SS_SALES_PRICE) AS REVENUE
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1176 AND 1176 + 11
			GROUP BY SS_STORE_SK, SS_ITEM_SK) SC
WHERE SB.SS_STORE_SK = SC.SS_STORE_SK
		AND SC.REVENUE <= 0.1 * SB.AVE
		AND S_STORE_SK = SC.SS_STORE_SK
		AND I_ITEM_SK = SC.SS_ITEM_SK
ORDER BY S_STORE_NAME, I_ITEM_DESC
LIMIT 100;
