SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;

---

SELECT CC_CALL_CENTER_ID CALL_CENTER, CC_NAME CALL_CENTER_NAME, CC_MANAGER MANAGER, SUM(CR_NET_LOSS) RETURNS_LOSS
FROM CALL_CENTER, CATALOG_RETURNS, DATE_DIM, CUSTOMER, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS,
	HOUSEHOLD_DEMOGRAPHICS
WHERE CR_CALL_CENTER_SK = CC_CALL_CENTER_SK
		AND CR_RETURNED_DATE_SK = D_DATE_SK
		AND CR_RETURNING_CUSTOMER_SK = C_CUSTOMER_SK
		AND CD_DEMO_SK = C_CURRENT_CDEMO_SK
		AND HD_DEMO_SK = C_CURRENT_HDEMO_SK
		AND CA_ADDRESS_SK = C_CURRENT_ADDR_SK
		AND D_YEAR = 1998
		AND D_MOY = 11
		AND ((CD_MARITAL_STATUS = 'M'
								AND CD_EDUCATION_STATUS = 'Unknown') OR(CD_MARITAL_STATUS = 'W'
																																																AND CD_EDUCATION_STATUS = 'Advanced Degree'))
		AND HD_BUY_POTENTIAL LIKE 'Unknown%'
		AND CA_GMT_OFFSET = -7
GROUP BY CC_CALL_CENTER_ID, CC_NAME, CC_MANAGER, CD_MARITAL_STATUS, CD_EDUCATION_STATUS
ORDER BY SUM(CR_NET_LOSS) DESC;
