SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;

---

SELECT COUNT(*)
FROM STORE_SALES, HOUSEHOLD_DEMOGRAPHICS, TIME_DIM, STORE
WHERE SS_SOLD_TIME_SK = TIME_DIM.T_TIME_SK
		AND SS_HDEMO_SK = HOUSEHOLD_DEMOGRAPHICS.HD_DEMO_SK
		AND SS_STORE_SK = S_STORE_SK
		AND TIME_DIM.T_HOUR = 20
		AND TIME_DIM.T_MINUTE >= 30
		AND HOUSEHOLD_DEMOGRAPHICS.HD_DEP_COUNT = 7
		AND STORE.S_STORE_NAME = 'ese'
ORDER BY COUNT(*)
LIMIT 100;
