WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;

---

WITH SSCI AS
		(SELECT SS_CUSTOMER_SK CUSTOMER_SK, SS_ITEM_SK ITEM_SK
			FROM STORE_SALES, DATE_DIM
			WHERE SS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY SS_CUSTOMER_SK, SS_ITEM_SK),
	CSCI AS
		(SELECT CS_BILL_CUSTOMER_SK CUSTOMER_SK,CS_ITEM_SK ITEM_SK
			FROM CATALOG_SALES,DATE_DIM
			WHERE CS_SOLD_DATE_SK = D_DATE_SK
					AND D_MONTH_SEQ BETWEEN 1200 AND 1200 + 11
			GROUP BY CS_BILL_CUSTOMER_SK,CS_ITEM_SK)
SELECT SUM(CASE
															WHEN SSCI.CUSTOMER_SK IS NOT NULL
																				AND CSCI.CUSTOMER_SK IS NULL THEN 1
															ELSE 0
											END) STORE_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) CATALOG_ONLY,
	SUM(CASE
									WHEN SSCI.CUSTOMER_SK IS NOT NULL
														AND CSCI.CUSTOMER_SK IS NOT NULL THEN 1
									ELSE 0
					END) STORE_AND_CATALOG
FROM SSCI
FULL OUTER JOIN CSCI ON (SSCI.CUSTOMER_SK = CSCI.CUSTOMER_SK
																									AND SSCI.ITEM_SK = CSCI.ITEM_SK)
LIMIT 100;
